package com.latentic.graspy.plan

import java.util.Locale

// The web's lists (apps/web/src/lib/country-languages.ts and locale.ts), code for code: PlacesTest holds
// them to it.

/** Every ISO 3166-1 region with the languages its learners are offered first, its main language first. */
val COUNTRY_LANGUAGES: Map<String, List<String>> = linkedMapOf(
    "AD" to listOf("ca", "es", "fr", "en"),
    "AE" to listOf("ar", "en"),
    "AF" to listOf("ps", "fa", "en"),
    "AG" to listOf("en"),
    "AI" to listOf("en"),
    "AL" to listOf("sq", "en"),
    "AM" to listOf("hy", "en"),
    "AO" to listOf("pt", "en"),
    "AQ" to listOf("en"),
    "AR" to listOf("es", "en"),
    "AS" to listOf("en", "sm"),
    "AT" to listOf("de", "en"),
    "AU" to listOf("en"),
    "AW" to listOf("nl", "en"),
    "AX" to listOf("sv", "fi", "en"),
    "AZ" to listOf("az", "ru", "en"),
    "BA" to listOf("bs", "hr", "sr", "en"),
    "BB" to listOf("en"),
    "BD" to listOf("bn", "en"),
    "BE" to listOf("nl", "fr", "en"),
    "BF" to listOf("fr", "en"),
    "BG" to listOf("bg", "en"),
    "BH" to listOf("ar", "en"),
    "BI" to listOf("fr", "rn", "en"),
    "BJ" to listOf("fr", "en"),
    "BL" to listOf("fr", "en"),
    "BM" to listOf("en"),
    "BN" to listOf("ms", "en"),
    "BO" to listOf("es", "qu", "ay", "en"),
    "BQ" to listOf("nl", "en"),
    "BR" to listOf("pt", "en"),
    "BS" to listOf("en"),
    "BT" to listOf("dz", "en"),
    "BV" to listOf("no"),
    "BW" to listOf("en", "tn"),
    "BY" to listOf("be", "ru", "en"),
    "BZ" to listOf("en", "es"),
    "CA" to listOf("en", "fr"),
    "CC" to listOf("en"),
    "CD" to listOf("fr", "sw", "ln", "en"),
    "CF" to listOf("fr", "sg", "en"),
    "CG" to listOf("fr", "ln", "en"),
    "CH" to listOf("de", "fr", "it", "en"),
    "CI" to listOf("fr", "en"),
    "CK" to listOf("en", "rar"),
    "CL" to listOf("es", "en"),
    "CM" to listOf("fr", "en"),
    "CN" to listOf("zh", "en"),
    "CO" to listOf("es", "en"),
    "CR" to listOf("es", "en"),
    "CU" to listOf("es", "en"),
    "CV" to listOf("pt", "en"),
    "CW" to listOf("nl", "en"),
    "CX" to listOf("en"),
    "CY" to listOf("el", "tr", "en"),
    "CZ" to listOf("cs", "en"),
    "DE" to listOf("de", "en"),
    "DJ" to listOf("fr", "ar", "en"),
    "DK" to listOf("da", "en"),
    "DM" to listOf("en"),
    "DO" to listOf("es", "en"),
    "DZ" to listOf("ar", "fr", "en"),
    "EC" to listOf("es", "en"),
    "EE" to listOf("et", "en"),
    "EG" to listOf("ar", "en"),
    "EH" to listOf("ar", "es", "fr", "en"),
    "ER" to listOf("ti", "ar", "en"),
    "ES" to listOf("es", "en"),
    "ET" to listOf("am", "en"),
    "FI" to listOf("fi", "sv", "en"),
    "FJ" to listOf("en", "fj", "hi"),
    "FK" to listOf("en"),
    "FM" to listOf("en"),
    "FO" to listOf("fo", "da", "en"),
    "FR" to listOf("fr", "en"),
    "GA" to listOf("fr", "en"),
    "GB" to listOf("en"),
    "GD" to listOf("en"),
    "GE" to listOf("ka", "en"),
    "GF" to listOf("fr"),
    "GG" to listOf("en"),
    "GH" to listOf("en"),
    "GI" to listOf("en"),
    "GL" to listOf("kl", "da", "en"),
    "GM" to listOf("en"),
    "GN" to listOf("fr", "en"),
    "GP" to listOf("fr"),
    "GQ" to listOf("es", "fr", "pt", "en"),
    "GR" to listOf("el", "en"),
    "GS" to listOf("en"),
    "GT" to listOf("es", "en"),
    "GU" to listOf("en", "ch"),
    "GW" to listOf("pt", "en"),
    "GY" to listOf("en"),
    "HK" to listOf("zh", "en"),
    "HM" to listOf("en"),
    "HN" to listOf("es", "en"),
    "HR" to listOf("hr", "en"),
    "HT" to listOf("fr", "ht", "en"),
    "HU" to listOf("hu", "en"),
    "ID" to listOf("id", "en"),
    "IE" to listOf("en", "ga"),
    "IL" to listOf("he", "ar", "en"),
    "IM" to listOf("en"),
    "IN" to listOf("hi", "en", "bn", "te", "mr", "ta", "ur", "gu", "kn", "ml"),
    "IO" to listOf("en"),
    "IQ" to listOf("ar", "ku", "en"),
    "IR" to listOf("fa", "en"),
    "IS" to listOf("is", "en"),
    "IT" to listOf("it", "en"),
    "JE" to listOf("en", "fr"),
    "JM" to listOf("en"),
    "JO" to listOf("ar", "en"),
    "JP" to listOf("ja", "en"),
    "KE" to listOf("sw", "en"),
    "KG" to listOf("ky", "ru", "en"),
    "KH" to listOf("km", "en"),
    "KI" to listOf("en", "gil"),
    "KM" to listOf("ar", "fr"),
    "KN" to listOf("en"),
    "KP" to listOf("ko"),
    "KR" to listOf("ko", "en"),
    "KW" to listOf("ar", "en"),
    "KY" to listOf("en"),
    "KZ" to listOf("kk", "ru", "en"),
    "LA" to listOf("lo", "en"),
    "LB" to listOf("ar", "en", "fr"),
    "LC" to listOf("en"),
    "LI" to listOf("de", "en"),
    "LK" to listOf("si", "ta", "en"),
    "LR" to listOf("en"),
    "LS" to listOf("en", "st"),
    "LT" to listOf("lt", "en"),
    "LU" to listOf("fr", "de", "lb", "en"),
    "LV" to listOf("lv", "en"),
    "LY" to listOf("ar", "en"),
    "MA" to listOf("ar", "fr", "en"),
    "MC" to listOf("fr", "en"),
    "MD" to listOf("ro", "ru", "en"),
    "ME" to listOf("sr", "en"),
    "MF" to listOf("fr", "en"),
    "MG" to listOf("mg", "fr", "en"),
    "MH" to listOf("en", "mh"),
    "MK" to listOf("mk", "en"),
    "ML" to listOf("fr", "en"),
    "MM" to listOf("my", "en"),
    "MN" to listOf("mn", "en"),
    "MO" to listOf("zh", "pt", "en"),
    "MP" to listOf("en"),
    "MQ" to listOf("fr"),
    "MR" to listOf("ar", "fr"),
    "MS" to listOf("en"),
    "MT" to listOf("mt", "en"),
    "MU" to listOf("en", "fr"),
    "MV" to listOf("dv", "en"),
    "MW" to listOf("en", "ny"),
    "MX" to listOf("es", "en"),
    "MY" to listOf("ms", "en", "zh", "ta"),
    "MZ" to listOf("pt", "en"),
    "NA" to listOf("en", "af"),
    "NC" to listOf("fr"),
    "NE" to listOf("fr", "en"),
    "NF" to listOf("en"),
    "NG" to listOf("en", "pcm", "yo", "ha", "ig"),
    "NI" to listOf("es", "en"),
    "NL" to listOf("nl", "en"),
    "NO" to listOf("no", "en"),
    "NP" to listOf("ne", "en"),
    "NR" to listOf("en"),
    "NU" to listOf("en"),
    "NZ" to listOf("en", "mi"),
    "OM" to listOf("ar", "en"),
    "PA" to listOf("es", "en"),
    "PE" to listOf("es", "en"),
    "PF" to listOf("fr"),
    "PG" to listOf("en", "tpi", "ho"),
    "PH" to listOf("en", "fil"),
    "PK" to listOf("ur", "en"),
    "PL" to listOf("pl", "en"),
    "PM" to listOf("fr"),
    "PN" to listOf("en"),
    "PR" to listOf("es", "en"),
    "PS" to listOf("ar", "en"),
    "PT" to listOf("pt", "en"),
    "PW" to listOf("en", "pau"),
    "PY" to listOf("es", "gn", "en"),
    "QA" to listOf("ar", "en"),
    "RE" to listOf("fr"),
    "RO" to listOf("ro", "en"),
    "RS" to listOf("sr", "en"),
    "RU" to listOf("ru", "en"),
    "RW" to listOf("rw", "en", "fr"),
    "SA" to listOf("ar", "en"),
    "SB" to listOf("en"),
    "SC" to listOf("en", "fr", "crs"),
    "SD" to listOf("ar", "en"),
    "SE" to listOf("sv", "en"),
    "SG" to listOf("en", "zh", "ms", "ta"),
    "SH" to listOf("en"),
    "SI" to listOf("sl", "en"),
    "SJ" to listOf("no"),
    "SK" to listOf("sk", "en"),
    "SL" to listOf("en"),
    "SM" to listOf("it", "en"),
    "SN" to listOf("fr", "wo", "en"),
    "SO" to listOf("so", "ar", "en"),
    "SR" to listOf("nl", "en"),
    "SS" to listOf("en", "ar"),
    "ST" to listOf("pt"),
    "SV" to listOf("es", "en"),
    "SX" to listOf("nl", "en"),
    "SY" to listOf("ar", "en", "ku"),
    "SZ" to listOf("en", "ss"),
    "TC" to listOf("en"),
    "TD" to listOf("fr", "ar", "en"),
    "TF" to listOf("fr"),
    "TG" to listOf("fr", "en"),
    "TH" to listOf("th", "en"),
    "TJ" to listOf("tg", "ru", "en"),
    "TK" to listOf("en"),
    "TL" to listOf("pt", "tet", "en"),
    "TM" to listOf("tk", "ru", "en"),
    "TN" to listOf("ar", "fr", "en"),
    "TO" to listOf("en", "to"),
    "TR" to listOf("tr", "en"),
    "TT" to listOf("en"),
    "TV" to listOf("en"),
    "TW" to listOf("zh", "en"),
    "TZ" to listOf("sw", "en"),
    "UA" to listOf("uk", "ru", "en"),
    "UG" to listOf("en", "sw"),
    "UM" to listOf("en"),
    "US" to listOf("en", "es"),
    "UY" to listOf("es", "en"),
    "UZ" to listOf("uz", "ru", "en"),
    "VA" to listOf("it", "la", "en"),
    "VC" to listOf("en"),
    "VE" to listOf("es", "en"),
    "VG" to listOf("en"),
    "VI" to listOf("en"),
    "VN" to listOf("vi", "en"),
    "VU" to listOf("bi", "fr", "en"),
    "WF" to listOf("fr"),
    "WS" to listOf("sm", "en"),
    "YE" to listOf("ar", "en"),
    "YT" to listOf("fr"),
    "ZA" to listOf("en", "af", "zu", "xh"),
    "ZM" to listOf("en"),
    "ZW" to listOf("en", "sn", "nd"),
)

/** The languages any learner may choose, beyond their country's own. */
val SUPPORTED_LANGUAGES: List<String> = listOf("ar", "en", "fr", "es", "yo", "pcm", "ha", "ig", "ps", "fa", "so", "sw", "am", "ku", "ur", "bn", "pt", "hi", "zh", "ru", "de", "it", "ja")

// Names Android's locale data lacks, as the web names them.
private val ENGLISH_LANGUAGE_NAMES = mapOf("pcm" to "Nigerian Pidgin")
private val NATIVE_LANGUAGE_NAMES = mapOf("yo" to "Èdè Yorùbá", "pcm" to "Naijá")
private val COUNTRY_NAMES = mapOf("OTHER" to "Other", "PS" to "Palestine")

fun countryName(code: String, display: Locale = Locale.ENGLISH): String =
    COUNTRY_NAMES[code] ?: Locale.Builder().setRegion(code).build().getDisplayCountry(display).ifBlank { code }

fun languageName(code: String, display: Locale = Locale.ENGLISH): String {
    val name = Locale.forLanguageTag(code).getDisplayLanguage(display)
    return if (name.isBlank() || name == code) ENGLISH_LANGUAGE_NAMES[code] ?: code else name
}

fun languageNativeName(code: String): String = NATIVE_LANGUAGE_NAMES[code] ?: languageName(code, Locale.forLanguageTag(code))

/** "Français (French)"; a name the learner reads either way appears once. */
fun languageLabel(code: String, display: Locale): String {
    val native = languageNativeName(code)
    val known = languageName(code, display)
    return if (native == known) native else "$native ($known)"
}

/** Countries by English name; the suggested one first. */
fun countriesInOrder(suggested: String?): List<String> {
    val all = COUNTRY_LANGUAGES.keys.sortedBy { countryName(it) }
    return listOfNotNull(suggested?.takeIf(COUNTRY_LANGUAGES::containsKey)) + all.filter { it != suggested }
}

/** A plan's code for a country or language it may name only in English. */
fun countryCodeOf(value: String): String? =
    value.takeIf(COUNTRY_LANGUAGES::containsKey) ?: COUNTRY_LANGUAGES.keys.firstOrNull { countryName(it) == value }

fun languageCodeOf(value: String): String? {
    val all = (COUNTRY_LANGUAGES.values.flatten() + SUPPORTED_LANGUAGES).toSet()
    return value.takeIf(all::contains) ?: all.firstOrNull { languageName(it) == value }
}
