package com.latentic.graspy.localization

/**
 * Signing in, choosing who is learning, and managing the account's learners, worded as the web app
 * words them. English, Yorùbá and Arabic are the web's own text; Pidgin is written for this app.
 */
data class AccountCopy(
    val signInTitle: String,
    val signInBody: String,
    val signIn: String,
    val signingIn: String,
    val noPassword: String,
    val signInFailed: String,
    val noGoogleAccount: String,
    val title: String,
    val body: String,
    val bodyFirst: String,
    val signedInAs: String,
    val back: String,
    val inUse: String,
    val addTile: String,
    val full: String,
    val devicePlan: String,
    val otherAccount: String,
    val opening: String,
    val loadFailed: String,
    val tryAgain: String,
    val failed: String,
    val unsent: String,
    val addTitle: String,
    val addBody: String,
    val nameLabel: String,
    val guardian: String,
    val addButton: String,
    val cancel: String,
    val manageTitle: String,
    val manageBody: String,
    val rename: String,
    val save: String,
    val remove: String,
    val removeConfirm: String,
    val removeYes: String,
    val deleteTitle: String,
    val deleteBody: String,
    val deleteButton: String,
    val deleteConfirm: String,
    val deleteYes: String,
    val learningAs: String,
    val switchLearner: String,
    val manageLearners: String,
    val signOut: String,
    val signOutUnsent: String,
    val signOutAnyway: String,
    val signingOut: String,
)

fun String.withName(name: String): String = replace("{name}", name)

fun String.withEmail(email: String): String = replace("{email}", email)

fun accountCopyFor(language: InterfaceLanguage): AccountCopy = when (language) {
    InterfaceLanguage.ENGLISH -> ENGLISH
    InterfaceLanguage.YORUBA -> YORUBA
    InterfaceLanguage.PIDGIN -> PIDGIN
    InterfaceLanguage.ARABIC -> ARABIC
}

private val ENGLISH = AccountCopy(
    signInTitle = "Sign in to graspy",
    signInBody = "Pick up your plan and progress on any device. A parent signs in once, then adds each child as a learner.",
    signIn = "Sign in with Google",
    signingIn = "Signing in…",
    noPassword = "graspy keeps no password: Google confirms it's you.",
    signInFailed = "Sign-in did not work. Check your connection, then try again.",
    noGoogleAccount = "No Google account is available on this device.",
    title = "Who's learning?",
    body = "Choose who is learning on this device. Each learner has their own plan and progress.",
    bodyFirst = "Add the first learner on this account: yourself, or your child.",
    signedInAs = "Signed in as {email}",
    back = "Back",
    inUse = "Learning on this device",
    addTile = "Add learner",
    full = "This account has 8 learners, the most it can hold. Remove one on the Learners page to add another.",
    devicePlan = "The plan already on this device goes to the learner you choose, or to one you add.",
    otherAccount = "Use another Google account",
    opening = "Opening…",
    loadFailed = "The learners could not be loaded. Check your connection, then try again.",
    tryAgain = "Try again",
    failed = "That did not work. Check your connection, then try again.",
    unsent = "Some changes have not reached graspy yet. Connect to the internet, then switch, so nothing is lost.",
    addTitle = "Add a learner",
    addBody = "They get their own plan and progress. You can rename or remove them later.",
    nameLabel = "Learner's name",
    guardian = "I'm this learner, or their parent or guardian",
    addButton = "Add",
    cancel = "Cancel",
    manageTitle = "Learners",
    manageBody = "Rename or remove the learners on this account.",
    rename = "Rename",
    save = "Save",
    remove = "Remove",
    removeConfirm = "Remove {name}? Their plan, progress, lessons and conversations are deleted from graspy. This can't be undone.",
    removeYes = "Remove {name}",
    deleteTitle = "Delete your account",
    deleteBody = "This deletes every learner on this account from graspy, and signs you out. Your Google account itself stays with Google.",
    deleteButton = "Delete my account",
    deleteConfirm = "Delete this account? Every learner's plan, progress, lessons and conversations are deleted from graspy. This can't be undone.",
    deleteYes = "Yes, delete my account",
    learningAs = "Learning as {name}",
    switchLearner = "Switch learner",
    manageLearners = "Learners",
    signOut = "Sign out",
    signOutUnsent = "Some changes have not reached graspy yet. If you sign out now, they are lost.",
    signOutAnyway = "Sign out anyway",
    signingOut = "Signing out…",
)

private val YORUBA = AccountCopy(
    signInTitle = "Wọlé sí graspy",
    signInBody = "Máa bá ètò àti ìtẹ̀síwájú rẹ lọ lórí ẹ̀rọ èyíkéyìí. Òbí á wọlé lẹ́ẹ̀kan, lẹ́yìn náà á fi ọmọ kọ̀ọ̀kan kún un gẹ́gẹ́ bí akẹ́kọ̀ọ́.",
    signIn = "Wọlé pẹ̀lú Google",
    signingIn = "Ó ń wọlé…",
    noPassword = "graspy kò tọ́jú ọ̀rọ̀ aṣínà kankan: Google ló ń jẹ́rìí pé ìwọ ni.",
    signInFailed = "Ìwọlé kò ṣiṣẹ́. Ṣàyẹ̀wò ìsopọ̀ rẹ, kí o sì tún gbìyànjú.",
    noGoogleAccount = "Kò sí àkọọ́lẹ̀ Google kankan lórí ẹ̀rọ yìí.",
    title = "Ta ló ń kẹ́kọ̀ọ́?",
    body = "Yan ẹni tó ń kẹ́kọ̀ọ́ lórí ẹ̀rọ yìí. Akẹ́kọ̀ọ́ kọ̀ọ̀kan ní ètò àti ìtẹ̀síwájú tirẹ̀.",
    bodyFirst = "Fi akẹ́kọ̀ọ́ àkọ́kọ́ kún àkántì yìí: ìwọ fúnra rẹ, tàbí ọmọ rẹ.",
    signedInAs = "O wọlé gẹ́gẹ́ bí {email}",
    back = "Padà",
    inUse = "Ó ń kẹ́kọ̀ọ́ lórí ẹ̀rọ yìí",
    addTile = "Fi akẹ́kọ̀ọ́ kún un",
    full = "Àkọọ́lẹ̀ yìí ní akẹ́kọ̀ọ́ 8, èyí tó pọ̀ jù tó lè gbà. Yọ ọ̀kan kúrò ní ojú-ìwé Àwọn akẹ́kọ̀ọ́ kí o tó fi òmíràn kún un.",
    devicePlan = "Ètò tó ti wà lórí ẹ̀rọ yìí yóò lọ sọ́dọ̀ akẹ́kọ̀ọ́ tí o bá yàn, tàbí èyí tí o bá fi kún un.",
    otherAccount = "Lo àkántì Google mìíràn",
    opening = "Ó ń ṣí…",
    loadFailed = "A kò rí àwọn akẹ́kọ̀ọ́ gbà. Ṣàyẹ̀wò ìsopọ̀ rẹ, kí o sì tún gbìyànjú.",
    tryAgain = "Tún gbìyànjú",
    failed = "Kò ṣiṣẹ́. Ṣàyẹ̀wò ìsopọ̀ rẹ, kí o sì tún gbìyànjú.",
    unsent = "Àwọn àyípadà kan kò tíì dé ọ̀dọ̀ graspy. Sopọ̀ mọ́ íńtánẹ́ẹ̀tì, kí o tó yí akẹ́kọ̀ọ́ padà, kí nǹkan kan má bàa sọnù.",
    addTitle = "Fi akẹ́kọ̀ọ́ kún un",
    addBody = "Wọn yóò ní ètò àti ìtẹ̀síwájú tiwọn. O lè yí orúkọ wọn padà tàbí yọ wọ́n kúrò nígbà míì.",
    nameLabel = "Orúkọ akẹ́kọ̀ọ́",
    guardian = "Èmi ni akẹ́kọ̀ọ́ yìí, tàbí òbí tàbí alágbàtọ́ rẹ̀",
    addButton = "Fi kún un",
    cancel = "Fagilé",
    manageTitle = "Àwọn akẹ́kọ̀ọ́",
    manageBody = "Yí orúkọ padà tàbí yọ àwọn akẹ́kọ̀ọ́ kúrò lórí àkọọ́lẹ̀ yìí.",
    rename = "Yí orúkọ padà",
    save = "Fi pamọ́",
    remove = "Yọ kúrò",
    removeConfirm = "Ṣé kí o yọ {name} kúrò? A máa pa ètò, ìtẹ̀síwájú, ẹ̀kọ́ àti ìjíròrò rẹ̀ rẹ́ kúrò nínú graspy. A kò lè dá a padà.",
    removeYes = "Yọ {name} kúrò",
    deleteTitle = "Pa àkọọ́lẹ̀ rẹ rẹ́",
    deleteBody = "Èyí máa pa gbogbo akẹ́kọ̀ọ́ tó wà lórí àkọọ́lẹ̀ yìí rẹ́ kúrò nínú graspy, yóò sì mú ọ jáde. Àkọọ́lẹ̀ Google rẹ fúnra rẹ̀ ṣì wà lọ́dọ̀ Google.",
    deleteButton = "Pa àkọọ́lẹ̀ mi rẹ́",
    deleteConfirm = "Ṣé kí o pa àkọọ́lẹ̀ yìí rẹ́? A máa pa ètò, ìtẹ̀síwájú, ẹ̀kọ́ àti ìjíròrò gbogbo akẹ́kọ̀ọ́ rẹ́ kúrò nínú graspy. A kò lè dá a padà.",
    deleteYes = "Bẹ́ẹ̀ ni, pa àkọọ́lẹ̀ mi rẹ́",
    learningAs = "{name} ló ń kẹ́kọ̀ọ́",
    switchLearner = "Yí akẹ́kọ̀ọ́ padà",
    manageLearners = "Àwọn akẹ́kọ̀ọ́",
    signOut = "Jáde",
    signOutUnsent = "Àwọn àyípadà kan kò tíì dé ọ̀dọ̀ graspy. Tí o bá jáde báyìí, wọ́n máa sọnù.",
    signOutAnyway = "Jáde bẹ́ẹ̀ náà",
    signingOut = "Ó ń jáde…",
)

private val PIDGIN = AccountCopy(
    signInTitle = "Sign in to graspy",
    signInBody = "Continue your plan and progress for any phone. Papa or mama go sign in once, then add every pikin as learner.",
    signIn = "Sign in with Google",
    signingIn = "E dey sign in…",
    noPassword = "graspy no dey keep password: na Google go confirm say na you.",
    signInFailed = "Sign-in no work. Check your network, then try again.",
    noGoogleAccount = "No Google account dey this phone.",
    title = "Who dey learn?",
    body = "Choose who dey learn for this phone. Every learner get their own plan and progress.",
    bodyFirst = "Add the first learner for this account: yourself, or your pikin.",
    signedInAs = "You sign in as {email}",
    back = "Go back",
    inUse = "E dey learn for this phone",
    addTile = "Add learner",
    full = "This account don get 8 learners, e no fit hold pass that. Remove one for the Learners page before you add another one.",
    devicePlan = "The plan wey dey this phone already go go to the learner wey you choose, or the one wey you add.",
    otherAccount = "Use another Google account",
    opening = "E dey open…",
    loadFailed = "We no fit bring the learners. Check your network, then try again.",
    tryAgain = "Try again",
    failed = "E no work. Check your network, then try again.",
    unsent = "Some changes never reach graspy yet. Connect to internet first, then switch, make nothing loss.",
    addTitle = "Add learner",
    addBody = "Dem go get their own plan and progress. You fit change their name or remove them later.",
    nameLabel = "Learner name",
    guardian = "Na me be this learner, or na me be their papa, mama or guardian",
    addButton = "Add",
    cancel = "Cancel",
    manageTitle = "Learners",
    manageBody = "Change the name of the learners for this account, or remove them.",
    rename = "Change name",
    save = "Save",
    remove = "Remove",
    removeConfirm = "Remove {name}? Their plan, progress, lessons and conversations go comot from graspy. You no fit bring am back.",
    removeYes = "Remove {name}",
    deleteTitle = "Delete your account",
    deleteBody = "This one go delete every learner for this account from graspy, and sign you out. Your Google account itself go still dey with Google.",
    deleteButton = "Delete my account",
    deleteConfirm = "Delete this account? Every learner plan, progress, lessons and conversations go comot from graspy. You no fit bring am back.",
    deleteYes = "Yes, delete my account",
    learningAs = "{name} dey learn",
    switchLearner = "Change learner",
    manageLearners = "Learners",
    signOut = "Sign out",
    signOutUnsent = "Some changes never reach graspy yet. If you sign out now, dem go loss.",
    signOutAnyway = "Sign out anyway",
    signingOut = "E dey sign out…",
)

private val ARABIC = AccountCopy(
    signInTitle = "سجّل الدخول إلى graspy",
    signInBody = "تابع خطتك وتقدّمك على أي جهاز. يسجّل وليّ الأمر الدخول مرة واحدة، ثم يضيف كل طفل متعلّمًا.",
    signIn = "تسجيل الدخول باستخدام Google",
    signingIn = "جارٍ تسجيل الدخول…",
    noPassword = "لا يحتفظ graspy بأي كلمة مرور: Google هو من يتحقّق من هويتك.",
    signInFailed = "لم ينجح تسجيل الدخول. تحقّق من اتصالك، ثم حاول مرة أخرى.",
    noGoogleAccount = "لا يوجد حساب Google على هذا الجهاز.",
    title = "من يتعلّم؟",
    body = "اختر من يتعلّم على هذا الجهاز. لكل متعلّم خطته وتقدّمه.",
    bodyFirst = "أضف أول متعلّم في هذا الحساب: أنت، أو طفلك.",
    signedInAs = "مسجّل الدخول باسم {email}",
    back = "رجوع",
    inUse = "يتعلّم على هذا الجهاز",
    addTile = "أضف متعلّمًا",
    full = "في هذا الحساب 8 متعلّمين، وهو الحد الأقصى. احذف واحدًا من صفحة المتعلّمين لتضيف آخر.",
    devicePlan = "الخطة الموجودة على هذا الجهاز تنتقل إلى المتعلّم الذي تختاره، أو إلى من تضيفه.",
    otherAccount = "استخدم حساب Google آخر",
    opening = "جارٍ الفتح…",
    loadFailed = "تعذّر تحميل المتعلّمين. تحقّق من اتصالك، ثم حاول مرة أخرى.",
    tryAgain = "حاول مرة أخرى",
    failed = "لم ينجح ذلك. تحقّق من اتصالك، ثم حاول مرة أخرى.",
    unsent = "بعض التغييرات لم تصل إلى graspy بعد. اتصل بالإنترنت ثم بدّل المتعلّم، حتى لا يضيع شيء.",
    addTitle = "أضف متعلّمًا",
    addBody = "ستكون له خطته وتقدّمه. يمكنك تغيير اسمه أو إزالته لاحقًا.",
    nameLabel = "اسم المتعلّم",
    guardian = "أنا هذا المتعلّم، أو والده أو وليّ أمره",
    addButton = "إضافة",
    cancel = "إلغاء",
    manageTitle = "المتعلّمون",
    manageBody = "غيّر أسماء المتعلّمين في هذا الحساب أو احذفهم.",
    rename = "تغيير الاسم",
    save = "حفظ",
    remove = "حذف",
    removeConfirm = "حذف {name}؟ تُحذف خطته وتقدّمه ودروسه ومحادثاته من graspy. لا يمكن التراجع عن ذلك.",
    removeYes = "احذف {name}",
    deleteTitle = "احذف حسابك",
    deleteBody = "يحذف هذا كل المتعلّمين في هذا الحساب من graspy، ويسجّل خروجك. يبقى حساب Google نفسه لدى Google.",
    deleteButton = "احذف حسابي",
    deleteConfirm = "حذف هذا الحساب؟ تُحذف خطط كل المتعلّمين وتقدّمهم ودروسهم ومحادثاتهم من graspy. لا يمكن التراجع عن ذلك.",
    deleteYes = "نعم، احذف حسابي",
    learningAs = "يتعلّم الآن: {name}",
    switchLearner = "تبديل المتعلّم",
    manageLearners = "المتعلّمون",
    signOut = "تسجيل الخروج",
    signOutUnsent = "بعض التغييرات لم تصل إلى graspy بعد. إذا سجّلت الخروج الآن فستضيع.",
    signOutAnyway = "سجّل الخروج على أي حال",
    signingOut = "جارٍ تسجيل الخروج…",
)
