package com.latentic.graspy.localization

/**
 * Signing in, choosing who is learning, and managing the account's learners, in the web app's own
 * words in every language (apps/web/src/locales).
 */
data class AccountCopy(
    val signIn: String,
    val signingIn: String,
    val signInFailed: String,
    val noGoogleAccount: String,
    val title: String,
    val back: String,
    val inUse: String,
    val addTile: String,
    val full: String,
    val devicePlan: String,
    val otherAccount: String,
    val opening: String,
    val loadFailed: String,
    val tryAgain: String,
    val failed: String,
    val offline: String,
    val unsent: String,
    val switchAnyway: String,
    val addTitle: String,
    val nameLabel: String,
    /** The consent the server requires, kept word for word. */
    val guardian: String,
    val addButton: String,
    val cancel: String,
    val manageTitle: String,
    val rename: String,
    val save: String,
    val remove: String,
    val removeConfirm: String,
    /** The confirming button: an imperative where the language has one. */
    val removeYes: String,
    val deleteAccount: String,
    val deleteBody: String,
    val deleteConfirm: String,
    val deleteYes: String,
    val learningAs: String,
    val switchLearner: String,
    val manageLearners: String,
    val signOut: String,
    val signOutUnsent: String,
    val signingOut: String,
)

fun String.withName(name: String): String = replace("{name}", name)

fun accountCopyFor(language: InterfaceLanguage): AccountCopy = when (language) {
    InterfaceLanguage.ENGLISH -> ENGLISH
    InterfaceLanguage.YORUBA -> YORUBA
    InterfaceLanguage.PIDGIN -> PIDGIN
    InterfaceLanguage.ARABIC -> ARABIC
}

private val ENGLISH = AccountCopy(
    signIn = "Continue with Google",
    signingIn = "Signing in…",
    signInFailed = "Sign-in didn't work. Try again.",
    noGoogleAccount = "Add a Google account to this device first.",
    title = "Who's learning?",
    back = "Back",
    inUse = "Learning on this device",
    addTile = "Add learner",
    full = "This account is full: 8 learners.",
    devicePlan = "This device's plan goes to who you choose.",
    otherAccount = "Use another account",
    opening = "Opening…",
    loadFailed = "The learners didn't load. Try again.",
    tryAgain = "Try again",
    failed = "That didn't work. Try again.",
    offline = "Connect to the internet first, so nothing is lost.",
    unsent = "Some changes haven't been sent. Switch anyway?",
    switchAnyway = "Switch",
    addTitle = "Add a learner",
    nameLabel = "Name",
    guardian = "I'm this learner, or their parent or guardian",
    addButton = "Add",
    cancel = "Cancel",
    manageTitle = "Learners",
    rename = "Rename",
    save = "Save",
    remove = "Remove",
    removeConfirm = "Remove {name} and all their progress? This can't be undone.",
    removeYes = "Remove",
    deleteAccount = "Delete account",
    deleteBody = "Deletes every learner and signs you out.",
    deleteConfirm = "Delete every learner and all their progress? This can't be undone.",
    deleteYes = "Delete",
    learningAs = "Learning as {name}",
    switchLearner = "Switch learner",
    manageLearners = "Learners",
    signOut = "Sign out",
    signOutUnsent = "Some changes haven't been sent. Sign out anyway?",
    signingOut = "Signing out…",
)

private val YORUBA = AccountCopy(
    signIn = "Tẹ̀síwájú pẹ̀lú Google",
    signingIn = "Ó ń wọlé…",
    signInFailed = "Ìwọlé kò ṣiṣẹ́. Tún gbìyànjú.",
    noGoogleAccount = "Kọ́kọ́ fi àkọọ́lẹ̀ Google kún ẹ̀rọ yìí.",
    title = "Ta ló ń kẹ́kọ̀ọ́?",
    back = "Padà",
    inUse = "Ó ń kẹ́kọ̀ọ́ lórí ẹ̀rọ yìí",
    addTile = "Fi akẹ́kọ̀ọ́ kún un",
    full = "Àkọọ́lẹ̀ yìí ti kún: akẹ́kọ̀ọ́ 8.",
    devicePlan = "Ètò ẹ̀rọ yìí yóò lọ sọ́dọ̀ ẹni tí o bá yàn.",
    otherAccount = "Lo àkántì mìíràn",
    opening = "Ó ń ṣí…",
    loadFailed = "Àwọn akẹ́kọ̀ọ́ kò ṣí. Tún gbìyànjú.",
    tryAgain = "Tún gbìyànjú",
    failed = "Kò ṣiṣẹ́. Tún gbìyànjú.",
    offline = "Kọ́kọ́ sopọ̀ mọ́ íńtánẹ́ẹ̀tì, kí nǹkan kan má bàa sọnù.",
    unsent = "A kò tíì fi àwọn àyípadà kan ránṣẹ́. Ṣé kí o yí akẹ́kọ̀ọ́ padà bẹ́ẹ̀ náà?",
    switchAnyway = "Yí padà",
    addTitle = "Fi akẹ́kọ̀ọ́ kún un",
    nameLabel = "Orúkọ",
    guardian = "Èmi ni akẹ́kọ̀ọ́ yìí, tàbí òbí tàbí alágbàtọ́ rẹ̀",
    addButton = "Fi kún un",
    cancel = "Fagilé",
    manageTitle = "Àwọn akẹ́kọ̀ọ́",
    rename = "Yí orúkọ padà",
    save = "Fi pamọ́",
    remove = "Yọ kúrò",
    removeConfirm = "Ṣé kí o yọ {name} àti gbogbo ìlọsíwájú rẹ̀ kúrò? A kò lè dá a padà.",
    removeYes = "Yọ kúrò",
    deleteAccount = "Pa àkọọ́lẹ̀ rẹ́",
    deleteBody = "Ó máa pa gbogbo akẹ́kọ̀ọ́ rẹ́, yóò sì mú ọ jáde.",
    deleteConfirm = "Ṣé kí o pa gbogbo akẹ́kọ̀ọ́ àti gbogbo ìlọsíwájú wọn rẹ́? A kò lè dá a padà.",
    deleteYes = "Pa á rẹ́",
    learningAs = "{name} ló ń kẹ́kọ̀ọ́",
    switchLearner = "Yí akẹ́kọ̀ọ́ padà",
    manageLearners = "Àwọn akẹ́kọ̀ọ́",
    signOut = "Jáde",
    signOutUnsent = "A kò tíì fi àwọn àyípadà kan ránṣẹ́. Ṣé kí o jáde bẹ́ẹ̀ náà?",
    signingOut = "Ó ń jáde…",
)

private val PIDGIN = AccountCopy(
    signIn = "Continue with Google",
    signingIn = "E dey sign in…",
    signInFailed = "Sign-in no work. Try again.",
    noGoogleAccount = "Add Google account to this device first.",
    title = "Who dey learn?",
    back = "Go back",
    inUse = "E dey learn for this device",
    addTile = "Add learner",
    full = "This account don full: 8 learners.",
    devicePlan = "This device plan go belong to who you choose.",
    otherAccount = "Use another account",
    opening = "E dey open…",
    loadFailed = "The learners no load. Try again.",
    tryAgain = "Try again",
    failed = "E no work. Try again.",
    offline = "Connect to internet first, make nothing loss.",
    unsent = "Some changes never send. You still wan change learner?",
    switchAnyway = "Change",
    addTitle = "Add learner",
    nameLabel = "Name",
    guardian = "Na me be this learner, or na me be im papa, mama or guardian",
    addButton = "Add",
    cancel = "Cancel",
    manageTitle = "Learners",
    rename = "Change name",
    save = "Save",
    remove = "Remove",
    removeConfirm = "Remove {name} and all im progress? You no fit bring am back.",
    removeYes = "Remove",
    deleteAccount = "Delete account",
    deleteBody = "E go delete every learner and sign you out.",
    deleteConfirm = "Delete every learner and all dem progress? You no fit bring am back.",
    deleteYes = "Delete",
    learningAs = "{name} dey learn",
    switchLearner = "Change learner",
    manageLearners = "Learners",
    signOut = "Sign out",
    signOutUnsent = "Some changes never send. You still wan sign out?",
    signingOut = "E dey sign out…",
)

private val ARABIC = AccountCopy(
    signIn = "المتابعة باستخدام Google",
    signingIn = "جارٍ تسجيل الدخول…",
    signInFailed = "لم ينجح تسجيل الدخول. حاول مرة أخرى.",
    noGoogleAccount = "أضف حساب Google إلى هذا الجهاز أولًا.",
    title = "من يتعلّم؟",
    back = "رجوع",
    inUse = "يتعلّم على هذا الجهاز",
    addTile = "أضف متعلّمًا",
    full = "هذا الحساب ممتلئ: 8 متعلّمين.",
    devicePlan = "خطة هذا الجهاز تنتقل إلى من تختاره.",
    otherAccount = "استخدم حسابًا آخر",
    opening = "جارٍ الفتح…",
    loadFailed = "لم يُحمَّل المتعلّمون. حاول مرة أخرى.",
    tryAgain = "حاول مرة أخرى",
    failed = "لم ينجح ذلك. حاول مرة أخرى.",
    offline = "اتصل بالإنترنت أولًا حتى لا يضيع شيء.",
    unsent = "لم تُرسَل بعض التغييرات. هل تبدّل المتعلّم على أي حال؟",
    switchAnyway = "تبديل",
    addTitle = "أضف متعلّمًا",
    nameLabel = "الاسم",
    guardian = "أنا هذا المتعلّم، أو والده أو وليّ أمره",
    addButton = "إضافة",
    cancel = "إلغاء",
    manageTitle = "المتعلّمون",
    rename = "تغيير الاسم",
    save = "حفظ",
    remove = "حذف",
    removeConfirm = "حذف {name} وكل تقدّمه؟ لا يمكن التراجع عن ذلك.",
    removeYes = "احذف",
    deleteAccount = "حذف الحساب",
    deleteBody = "يحذف كل المتعلّمين ويسجّل خروجك.",
    deleteConfirm = "حذف كل المتعلّمين وكل تقدّمهم؟ لا يمكن التراجع عن ذلك.",
    deleteYes = "احذف",
    learningAs = "يتعلّم الآن: {name}",
    switchLearner = "تبديل المتعلّم",
    manageLearners = "المتعلّمون",
    signOut = "تسجيل الخروج",
    signOutUnsent = "لم تُرسَل بعض التغييرات. هل تسجّل الخروج على أي حال؟",
    signingOut = "جارٍ تسجيل الخروج…",
)
