package com.latentic.graspy.localization

/**
 * The app in Arabic, an interface language only: the teacher still speaks English, Yorùbá or Pidgin.
 * Text the web app also shows is the web's own Arabic. Numbers are written in digits, as the web writes
 * them, since the words the teacher says a table in are English.
 */
internal val ARABIC_COPY = AppCopy(
    subjects = mapOf("mathematics" to "الرياضيات", "everyday" to "الحياة اليومية", "english" to "الإنجليزية", "yoruba" to "اليوروبا"),
    topics = mapOf(
        "multiplication" to "جداول الضرب", "number" to "الأعداد والعدّ",
        "operations" to "الجمع والقسمة", "time" to "قراءة الساعة",
        "money" to "النايرا والكوبو", "shapes" to "الأشكال", "fractions" to "الكسور",
        "alphabet" to "الحروف والأصوات",
    ),
    tagline = "رياضيات تُصغي إلى طريقتك في الكلام.",
    introduction = "أجب بطبيعتك باليوروبا والإنجليزية أو بالبيدجن والإنجليزية.",
    appLanguage = "لغة التطبيق",
    phoneLanguage = "الهاتف",
    startPractice = "جرّب سؤال ضرب واحدًا",
    startLesson = "ابدأ الدرس",
    listen = "استمع",
    preparingTeacher = "جارٍ تجهيز المعلّمة…",
    practiceDetail = "قل إجابتك. يعرض graspy ما سمعه ويتحقّق من الحساب.",
    practise = "تدرّب",
    contribute = "المساهمة",
    recordEvaluation = "سجّل مجموعة التقييم",
    contributionDetail = "قدّم مثالًا بموافقتك يساعدنا على مقارنة نماذج الكلام.",
    record = "سجّل",
    back = "رجوع",
    prompt = "كم حاصل ضرب سبعة في ثمانية؟",
    practiceDisclosure = "تُحفظ إجابتك ليعرض graspy ما سمعه ويحسّن التقييم.",
    contributionDisclosure = "سيُستخدم تسجيلك في مجموعة بيانات تقييم الهاكاثون.",
    allowRecording = "اسمح بهذا التسجيل",
    consentRecorded = "التسجيل مسموح",
    languagePair = "طريقة الكلام",
    yorubaEnglish = "اليوروبا + الإنجليزية",
    pidginEnglish = "البيدجن + الإنجليزية",
    recordAnswer = "سجّل الإجابة",
    stopAndCheck = "توقّف وتحقّق",
    saving = "جارٍ التحقّق…",
    transcript = "سمع graspy",
    queued = "حُفظت الإجابة. ستُراجَع عند الاتصال.",
    retained = "الإجابة محفوظة على هذا الهاتف. انقر مرة أخرى لإعادة المحاولة.",
    uploaded = "رُفعت الإجابة.",
    feedbackQuestion = "هل حفظ graspy ما قلته وتحقّق من الحساب بشكل صحيح؟",
    correctFeedback = "صحيح — سبعة في ثمانية تساوي ستة وخمسين.",
    wrongAnswerTemplate = "سمعت %d. جرّب سبع مجموعات من ثمانية مرة أخرى.",
    notUnderstoodFeedback = "سمعت كلماتك، لكن لم أسمع عددًا نهائيًا. قل الإجابة مرة أخرى.",
    contributeTitle = "ساعد graspy على الإصغاء بشكل أفضل.",
    question = "السؤال",
    yes = "نعم",
    no = "لا",
    thanksForChecking = "شكرًا على التحقّق.",
    microphoneNeeded = "يلزم إذن الميكروفون لتسجيل إجابة.",
    recordingNotStarted = "لم يعمل الميكروفون. حاول مرة أخرى.",
    recordingNotSaved = "تعذّر حفظ إجابتك على هذا الهاتف. حاول مرة أخرى.",
    lesson = LessonCopy(
        steps = listOf("استمع", "ردّدها", "اسمع النتيجة"),
        eyebrow = "الرياضيات · الضرب",
        title = "جدول ضرب %1\$s",
        detail = "يرسل graspy رسالة صوتية. تردّ برسالة واحدة، من %1\$s في 1 إلى %1\$s في 12.",
        teacherPrompt = "ردّد جدول ضرب 1 من 1 في 1 إلى 1 في 12 في رسالة صوتية واحدة.",
        teacherPromptNext = "الآن جدول ضرب %1\$s. ردّده من %1\$s في 1 إلى %1\$s في 12 في رسالة صوتية واحدة.",
        teacherReady = "المعلّمة تستعد",
        teacherSpeaking = "المعلّمة تتكلّم",
        yourTurn = "دورك",
        sayItYourWay = "باليوروبا أو البيدجن أو الإنجليزية. قلها بطريقتك.",
        speakNow = "تكلّم الآن…",
        recordTable = "انقر لتسجيل رسالتك الصوتية",
        stopAndSend = "انتهيت",
        yourVoiceNote = "رسالتك الصوتية",
        listening = "يستمع",
        sending = "جارٍ الإرسال…",
        sent = "أُرسلت",
        analysing = "جارٍ التحقّق من إجابتك…",
        feedbackReady = "ملاحظات المعلّمة",
        factsCorrectTemplate = "%1\$d من %2\$d قيلت بشكل صحيح",
        missingFacts = "لم تُسمع",
        uncertainFacts = "قل هذه مرة أخرى مع الإجابة",
        wrongFacts = "غير صحيحة",
        heardTemplate = "سُمع %1\$d، والمتوقّع %2\$d",
        completeFeedback = "ممتاز. أكملت جدول ضرب %1\$s بشكل صحيح من 1 إلى 12.",
        retryFeedback = "محاولة جيدة. راجع الحقائق أدناه، ثم سجّل الجدول كاملًا مرة أخرى.",
        notUnderstoodFeedback = "لم أسمع جدول ضرب %1\$s. سجّله مرة أخرى ببطء، بدءًا من %1\$s في 1.",
        playAgain = "انقر لتسمع مرة أخرى",
        teacherAudioFailed = "تعذّر تحميل صوت المعلّمة.",
        retryTeacherAudio = "أعد تحميل صوت المعلّمة",
        waitingForTeacher = "نتحقّق من هذه الخطوة مع معلّمتك…",
        keptOnPhone = "رسالتك الصوتية محفوظة على هذا الهاتف وستُرسل عند الاتصال.",
        showWords = "اعرض الكلمات",
        showMaths = "اعرض الحساب",
        threadSubtitle = "جدول ضرب %1\$s",
        today = "اليوم",
        resultEyebrow = "نتيجة الجدول",
        sendFailed = "لم تصل هذه الرسالة إلى graspy. أرسلها مرة أخرى.",
        noSpeech = "لم أسمعك. انقر وقلها مرة أخرى.",
        couldNotCheck = "لم أتمكّن من التحقّق من هذه. لنسجّلها مرة أخرى.",
        noWords = "لم تُسمع كلمات",
        learnFact = "%1\$s في %2\$s يساوي %3\$s. أي %1\$s مجموعات من %2\$s.",
        askFact = "كم يساوي %1\$s في %2\$s؟",
        retryFacts = "الآن قل هذه الحقائق فقط مرة أخرى.",
        correctShort = "صحيح!",
        doneToday = "أحسنت. سنراجع جدول ضرب %1\$s مرة أخرى غدًا.",
        masteredTable = "أنت تعرف جدول ضرب %1\$s الآن. أحسنت.",
        finished = "أنهيت كل الجداول. أحسنت.",
        youSaid = "قلت %1\$d",
        tryAgain = "محاولة جيدة. قلها مرة أخرى.",
        factResultEyebrow = "النتيجة",
        chats = "المحادثات",
        openChat = "افتح المحادثة",
        numbersInWords = false,
    ),
    home = HomeCopy(
        tab = "الرئيسية",
        title = "دروسك",
        nextLesson = "الدرس التالي",
        loading = "جارٍ جلب دروسك…",
        refreshing = "نبحث عن دروس جديدة…",
        loadFailed = "لم تُحمَّل دروسك.",
        retry = "حاول مرة أخرى",
        noLessons = "لا توجد دروس لصفّك بعد.",
        mastered = "تعرفه",
        learnt = "تم تعلّمه",
        started = "بدأته",
        untouched = "ليس بعد",
        badges = "الشارات التي ربحتها",
        oneMoreDay = "يوم جيد آخر في %1\$s يربحك شارته.",
        almostThere = "اقتربت",
        startHere = "ابدأ من هنا",
        yourTeacher = "معلّمتك",
    ),
    onboarding = OnboardingCopy(
        whatClass = "في أي صف أنت؟",
        whichLanguage = "بأي لغة تحب أن تتكلّم؟",
        lessonLanguageNote = "تتكلّم المعلّمة الإنجليزية أو اليوروبا أو البيدجن. تُختار لغة كلمات التطبيق بعد ذلك، على حدة.",
        whichInterface = "بأي لغة تكون كلمات التطبيق؟",
        interfaceNote = "يغيّر هذا كلمات التطبيق على هذا الهاتف، لكل من يتعلّم عليه. تبقى الدروس باللغة التي اخترتها قبل ذلك.",
        followPhone = "لغة الهاتف",
        next = "تابع",
        classAndLanguage = "الصف واللغة",
        detectLanguage = "دع graspy يستمع",
        classLabels = ARABIC_CLASS_LABELS,
    ),
)
