package com.latentic.graspy.localization

/** The app in English. */
internal val ENGLISH_COPY = AppCopy(
    topics = mapOf(
        "multiplication" to "Times tables", "number" to "Numbers and counting",
        "operations" to "Adding and sharing", "time" to "Telling the time",
        "money" to "Naira and kobo", "shapes" to "Shapes", "fractions" to "Fractions",
        "alphabet" to "Letters and sounds",
    ),
    transcript = "graspy heard",
    notUnderstoodFeedback = "I didn't hear a number. Say the answer again.",
    microphoneNeeded = "Allow the microphone to record your answer.",
    recordingNotStarted = "The microphone didn't start. Try again.",
    recordingNotSaved = "Your answer wasn't saved. Try again.",
    lesson = LessonCopy(
        teacherSpeaking = "Teacher is speaking",
        yourTurn = "Your turn",
        sayItYourWay = "Say it your way.",
        speakNow = "Speak now…",
        recordTable = "Record your answer",
        stopAndSend = "I'm done",
        sending = "Sending…",
        analysing = "Checking your answer…",
        notUnderstoodFeedback = "I couldn't hear the %1\$s times table. Say it again slowly.",
        playAgain = "Hear again",
        teacherAudioFailed = "The teacher's voice didn't load.",
        waitingForTeacher = "Checking with your teacher…",
        noSpeech = "I couldn't hear you. Say it again.",
        couldNotCheck = "I couldn't check that. Say it again.",
        learnFact = "%1\$s times %2\$s is %3\$s.",
        correctShort = "Correct!",
        tryAgain = "Good try. Say it again.",
        loading = "Getting your lesson…",
        loadFailed = "Your lesson didn't load.",
    ),
    home = HomeCopy(
        title = "Your lessons",
        loading = "Getting your lessons…",
        loadFailed = "Your lessons didn't load.",
        retry = "Try again",
        noLessons = "No lessons for your class yet.",
        mastered = "Known",
        learnt = "Learnt",
        started = "Started",
        untouched = "Not yet",
        badges = "Your badges",
        oneMoreDay = "One more good day on %1\$s wins its badge.",
        almostThere = "Almost there",
        startHere = "START HERE",
    ),
    onboarding = OnboardingCopy(
        whatClass = "Your class",
        whichLanguage = "Lesson language",
        lessonLanguageNote = "The teacher speaks English, Yorùbá or Pidgin.",
        whichInterface = "App language",
        followLessons = "Same as the lessons",
        next = "Continue",
        classAndLanguage = "Class and language",
        detectLanguage = "Let graspy listen",
        classLabels = NIGERIAN_CLASS_LABELS,
    ),
)
