package com.latentic.graspy.localization

// The web app's own words (apps/web/src/locales), key for key: WebWordsTest holds them to it.

/** The learner's app beyond voice lessons, in the web app's words. */
data class LearnCopy(
    val nav: NavCopy,
    val home: PlanHomeCopy,
    val subject: SubjectCopy,
    val plan: PlanCopy,
    val planBuilding: PlanBuildingCopy,
    val you: YouCopy,
    val level: LevelCopy,
    val details: DetailsCopy,
    val voice: VoiceNoteCopy,
    val chat: ChatCopy,
    val ask: AskCopy,
    val lesson: TopicLessonCopy,
    val onboarding: PlanOnboardingCopy,
)

/** The tab bar. */
data class NavCopy(
    val label: String,
    val home: String,
    val subjects: String,
    val ask: String,
    val you: String,
)

/** Home's plan sections. */
data class PlanHomeCopy(
    val continueTitle: String,
    val `continue`: String,
    val start: String,
    val resumeMeta: String,
    val subjectsTitle: String,
    val seeAll: String,
    val noSubjects: String,
    val topicsCompleted: String,
    val topicsCompletedOf: String,
    val startLearning: String,
    val tryTitle: String,
    val askTitle: String,
    val askDetail: String,
    val practiseTitle: String,
    val practiseDetail: String,
    val planTitle: String,
    val planDetail: String,
    val practiseDraft: String,
    val practiseDraftAny: String,
    val planDraft: String,
)

/** A subject and its topics. */
data class SubjectCopy(
    val back: String,
    val progress: String,
    val progressLabel: String,
    val learnt: String,
    val ready: String,
    val notStarted: String,
    val goal: String,
    val lessonsCompleted: String,
    val topicsLoading: String,
)

/** The plan itself. */
data class PlanCopy(
    val edit: String,
    val buildFailed: String,
    val tryAgain: String,
)

/** A plan being made. */
data class PlanBuildingCopy(
    val making: String,
)

/** The You tab. */
data class YouCopy(
    val progress: String,
    val details: String,
    val country: String,
    val language: String,
    val grade: String,
    val editSubjects: String,
    val practice: String,
    val practiceRight: String,
    val practiceNone: String,
    val change: String,
    val account: String,
    val learningAs: String,
    val switchLearner: String,
    val manageLearners: String,
    val signOut: String,
    val onMyOwn: String,
)

/** Levels after secondary school. */
data class LevelCopy(
    val undergraduate: String,
    val graduate: String,
)

/** The learner's details, and whether they get a new plan. */
data class DetailsCopy(
    val back: String,
    val title: String,
    val save: String,
    val askTitle: String,
    val askBody: String,
    val newPlan: String,
    val keepPlan: String,
)

/** Voice lessons, and the note shown before the first. */
data class VoiceNoteCopy(
    val title: String,
    val start: String,
    val note: String,
    val ok: String,
)

/** Ask: the tutor. */
data class ChatCopy(
    val openTutor: String,
    val newTutorMessage: String,
    val draftPlaceholderTopic: String,
    val aiTutorTitle: String,
    val aiTutorWelcome: String,
    val send: String,
    val stop: String,
    val tutorThinking: String,
    val tutorError: String,
    val temporaryProblem: String,
    val suggestedQuestions: String,
    val viewUnavailable: String,
    val openLesson: String,
    val openSubject: String,
    val seeSubjects: String,
    val activity: Map<String, String>,
    val planChangeFailed: String,
    val changingPlan: String,
    val confirmTitle: String,
    val confirmRebuild: String,
    val confirmRemove: String,
    val confirmYes: String,
    val confirmNo: String,
    val subjectsChanged: String,
    val topicAdded: String,
    val pathAdded: String,
    val pathTitle: String,
    val pathPlanning: String,
    val pathFailed: String,
    val pathSummary: String,
    val pathSummaryOneLevel: String,
    val pathMore: String,
    val pathAccept: String,
    val pathNotNow: String,
    val topicReady: String,
    val subjectReady: String,
)

/** Choosing what to ask about. */
data class AskCopy(
    val currentTopic: String,
    val open: String,
    val recent: String,
    val anythingTitle: String,
    val anything: String,
    val chooseTopic: String,
    val change: String,
    val changeTitle: String,
    val close: String,
    val anythingWelcome: String,
    val anythingPlaceholder: String,
    val allOf: String,
    val wholeSubject: String,
)

/** A topic's lesson. */
data class TopicLessonCopy(
    val loading: String,
    val loadFailed: String,
    val tryAgain: String,
    val backTo: String,
)

data class PlanOnboardingStepsProfileCopy(
    val title: String,
)

data class PlanOnboardingStepsSubjectsCopy(
    val title: String,
)

data class PlanOnboardingStepsCopy(
    val profile: PlanOnboardingStepsProfileCopy,
    val subjects: PlanOnboardingStepsSubjectsCopy,
)

data class PlanOnboardingProfileCopy(
    val countryLabel: String,
    val countryPlaceholder: String,
    val languageLabel: String,
    val languagePlaceholder: String,
    val gradeLabel: String,
    val gradePlaceholder: String,
    val suggested: String,
    val allCountries: String,
    val allLanguages: String,
    val noResults: String,
    val courseLabel: String,
    val coursePlaceholder: String,
    val gradeNeedsCountry: String,
    val gradesLoading: String,
    val gradesFailed: String,
    val systemLabel: String,
    val afterSchool: String,
)

data class PlanOnboardingSubjectsCopy(
    val heading: String,
    val recommended: String,
    val limit: String,
    val finding: String,
    val loadFailed: String,
    val tryAgain: String,
)

data class PlanOnboardingGeneratingStagesAnalyzingCopy(
    val label: String,
)

data class PlanOnboardingGeneratingStagesGeneratingCopy(
    val label: String,
)

data class PlanOnboardingGeneratingStagesPersonalizingCopy(
    val label: String,
)

data class PlanOnboardingGeneratingStagesCopy(
    val analyzing: PlanOnboardingGeneratingStagesAnalyzingCopy,
    val generating: PlanOnboardingGeneratingStagesGeneratingCopy,
    val personalizing: PlanOnboardingGeneratingStagesPersonalizingCopy,
)

data class PlanOnboardingGeneratingCopy(
    val title: String,
    val wait: String,
    val failed: String,
    val failedBody: String,
    val tryAgain: String,
    val adjust: String,
    val stages: PlanOnboardingGeneratingStagesCopy,
)

data class PlanOnboardingReadyCopy(
    val title: String,
    val body: String,
    val `continue`: String,
)

/** Making a plan: the learner, their subjects, then the plan. */
data class PlanOnboardingCopy(
    val stepOf: String,
    val back: String,
    val next: String,
    val start: String,
    val settingUp: String,
    val steps: PlanOnboardingStepsCopy,
    val profile: PlanOnboardingProfileCopy,
    val subjects: PlanOnboardingSubjectsCopy,
    val generating: PlanOnboardingGeneratingCopy,
    val ready: PlanOnboardingReadyCopy,
    val moreSubjects: String,
)

fun learnCopyFor(language: InterfaceLanguage): LearnCopy = when (language) {
    InterfaceLanguage.ENGLISH -> ENGLISH_LEARN
    InterfaceLanguage.YORUBA -> YORUBA_LEARN
    InterfaceLanguage.PIDGIN -> PIDGIN_LEARN
    InterfaceLanguage.ARABIC -> ARABIC_LEARN
}

private val ENGLISH_LEARN = LearnCopy(
    nav = NavCopy(
        label = "Main",
        home = "Home",
        subjects = "Subjects",
        ask = "Ask",
        you = "You",
    ),
    home = PlanHomeCopy(
        continueTitle = "Continue learning",
        `continue` = "Continue",
        start = "Start",
        resumeMeta = "{subject} · {grade}",
        subjectsTitle = "Your subjects",
        seeAll = "See all",
        noSubjects = "Your subjects appear here once your plan is ready.",
        topicsCompleted = "{completed} of {total} topics completed",
        topicsCompletedOf = "of {total} topics completed",
        startLearning = "Start learning",
        tryTitle = "Or try something new",
        askTitle = "Explain a topic",
        askDetail = "Ask any question",
        practiseTitle = "Practice",
        practiseDetail = "Try some questions",
        planTitle = "Get a study plan",
        planDetail = "For your exams",
        practiseDraft = "Give me three practice questions on {topic}, one at a time.",
        practiseDraftAny = "Give me three practice questions on what I am learning, one at a time.",
        planDraft = "Make me a study plan for my exams in ",
    ),
    subject = SubjectCopy(
        back = "All subjects",
        progress = "{done} of {total} learnt",
        progressLabel = "Progress",
        learnt = "Learnt",
        ready = "Ready",
        notStarted = "Not started",
        goal = "You asked for this",
        lessonsCompleted = "{completed} of {total} lessons",
        topicsLoading = "Loading topics...",
    ),
    plan = PlanCopy(
        edit = "Edit",
        buildFailed = "Your plan didn't build.",
        tryAgain = "Try again",
    ),
    planBuilding = PlanBuildingCopy(
        making = "Making your plan…",
    ),
    you = YouCopy(
        progress = "Your progress",
        details = "Your details",
        country = "Country",
        language = "Learning in",
        grade = "Level",
        editSubjects = "Edit your subjects",
        practice = "Your practice",
        practiceRight = "{right} of {answered} right",
        practiceNone = "No practice yet.",
        change = "Change",
        account = "Your account",
        learningAs = "Learning as {name}",
        switchLearner = "Switch learner",
        manageLearners = "Learners",
        signOut = "Sign out",
        onMyOwn = "Learning on my own",
    ),
    level = LevelCopy(
        undergraduate = "Undergraduate",
        graduate = "Graduate",
    ),
    details = DetailsCopy(
        back = "Back",
        title = "Your details",
        save = "Save changes",
        askTitle = "Make a new plan for these details?",
        askBody = "A new plan replaces the one you have.",
        newPlan = "Make a new plan",
        keepPlan = "Keep my plan",
    ),
    voice = VoiceNoteCopy(
        title = "Voice lessons",
        start = "Start",
        note = "graspy sends your voice to check your answers.",
        ok = "OK",
    ),
    chat = ChatCopy(
        openTutor = "Ask graspy",
        newTutorMessage = "New message from graspy",
        draftPlaceholderTopic = "Ask graspy about {topic}",
        aiTutorTitle = "graspy tutor",
        aiTutorWelcome = "Hi! Ask me anything about your lesson.",
        send = "Send",
        stop = "Stop",
        tutorThinking = "Thinking…",
        tutorError = "Something went wrong. Try again.",
        temporaryProblem = "That didn't get through. Try again.",
        suggestedQuestions = "Questions you could ask next",
        viewUnavailable = "This card could not be shown.",
        openLesson = "Open lesson",
        openSubject = "Open subject",
        seeSubjects = "See your subjects",
        activity = mapOf("calculate" to "Working out the numbers...", "open_subject" to "Opening the subject...", "open_topic" to "Finding the topic...", "add_topic" to "Adding the topic to your plan...", "propose_path" to "Planning a path...", "change_subjects" to "Updating your subjects...", "rebuild_plan" to "Getting ready to rebuild your plan...", "give_practice" to "Writing a question for you...", "give_passage" to "Writing a passage for you..."),
        planChangeFailed = "Your subjects didn't change. Try again.",
        changingPlan = "Updating your plan...",
        confirmTitle = "Confirm a change to your plan",
        confirmRebuild = "Rebuild your plan? Your progress is cleared.",
        confirmRemove = "Remove {subjects}? Their progress is cleared.",
        confirmYes = "Yes, go ahead",
        confirmNo = "Keep my plan",
        subjectsChanged = "Your subjects are updated.",
        topicAdded = "Added “{topic}” to {subject}.",
        pathAdded = "Added the path “{subject}” to your plan.",
        pathTitle = "A learning path",
        pathPlanning = "Planning a path to {goal}...",
        pathFailed = "Couldn't plan a path to {goal}. Try again later.",
        pathSummary = "{count} topics, from {from} to {to}",
        pathSummaryOneLevel = "{count} topics at {level}",
        pathMore = "and {count} more",
        pathAccept = "Add this path",
        pathNotNow = "Not now",
        topicReady = "“{topic}” is ready when you are.",
        subjectReady = "{subject} is ready when you are.",
    ),
    ask = AskCopy(
        currentTopic = "Your current topic",
        open = "Open chat",
        recent = "Recent chats",
        anythingTitle = "Ask generally",
        anything = "Ask anything",
        chooseTopic = "Choose a subject",
        change = "Change",
        changeTitle = "Change topic",
        close = "Close",
        anythingWelcome = "Ask me anything.",
        anythingPlaceholder = "Ask graspy anything",
        allOf = "All of {subject}",
        wholeSubject = "Whole subject",
    ),
    lesson = TopicLessonCopy(
        loading = "Preparing your lesson",
        loadFailed = "The lesson didn't load",
        tryAgain = "Try again",
        backTo = "Back to {subject}",
    ),
    onboarding = PlanOnboardingCopy(
        stepOf = "Step {current} of {total}",
        back = "Back",
        next = "Next",
        start = "Start learning",
        settingUp = "Setting up...",
        steps = PlanOnboardingStepsCopy(
            profile = PlanOnboardingStepsProfileCopy(
                title = "About you",
            ),
            subjects = PlanOnboardingStepsSubjectsCopy(
                title = "Your subjects",
            ),
        ),
        profile = PlanOnboardingProfileCopy(
            countryLabel = "Country",
            countryPlaceholder = "Search countries",
            languageLabel = "Language",
            languagePlaceholder = "Choose a language",
            gradeLabel = "Class",
            gradePlaceholder = "Choose your class",
            suggested = "Suggested",
            allCountries = "All countries",
            allLanguages = "All languages",
            noResults = "No matches",
            courseLabel = "Course",
            coursePlaceholder = "For example, Accounting",
            gradeNeedsCountry = "Choose your country first",
            gradesLoading = "Finding classes…",
            gradesFailed = "The classes didn't load. Check your connection.",
            systemLabel = "School system",
            afterSchool = "After secondary school",
        ),
        subjects = PlanOnboardingSubjectsCopy(
            heading = "Subjects",
            recommended = "Recommended",
            limit = "Up to {limit} subjects.",
            finding = "Finding subjects…",
            loadFailed = "The subjects didn't load. Check your connection.",
            tryAgain = "Try again",
        ),
        generating = PlanOnboardingGeneratingCopy(
            title = "Building your plan",
            wait = "This can take a minute.",
            failed = "Your plan didn't finish.",
            failedBody = "Check your connection and try again.",
            tryAgain = "Try again",
            adjust = "Change subjects",
            stages = PlanOnboardingGeneratingStagesCopy(
                analyzing = PlanOnboardingGeneratingStagesAnalyzingCopy(
                    label = "Reading your details",
                ),
                generating = PlanOnboardingGeneratingStagesGeneratingCopy(
                    label = "Choosing topics",
                ),
                personalizing = PlanOnboardingGeneratingStagesPersonalizingCopy(
                    label = "Putting them in order",
                ),
            ),
        ),
        ready = PlanOnboardingReadyCopy(
            title = "Your plan is ready",
            body = "{topics} topics",
            `continue` = "Start",
        ),
        moreSubjects = "+{count} more",
    ),
)

private val YORUBA_LEARN = LearnCopy(
    nav = NavCopy(
        label = "Ìtọ́sọ́nà",
        home = "Ilé",
        subjects = "Kókó-ẹ̀kọ́",
        ask = "Béèrè",
        you = "Ìwọ",
    ),
    home = PlanHomeCopy(
        continueTitle = "Máa bá ẹ̀kọ́ lọ",
        `continue` = "Tẹ̀síwájú",
        start = "Bẹ̀rẹ̀",
        resumeMeta = "{subject} · {grade}",
        subjectsTitle = "Àwọn kókó-ẹ̀kọ́ rẹ",
        seeAll = "Wo gbogbo rẹ̀",
        noSubjects = "Àwọn kókó-ẹ̀kọ́ rẹ yóò hàn níbí nígbà tí ètò rẹ bá ti ṣetán.",
        topicsCompleted = "{completed} nínú àkòrí {total} ti parí",
        topicsCompletedOf = "nínú àkòrí {total} ti parí",
        startLearning = "Bẹ̀rẹ̀ ẹ̀kọ́",
        tryTitle = "Tàbí gbìyànjú nǹkan tuntun",
        askTitle = "Ṣàlàyé àkòrí kan",
        askDetail = "Béèrè ìbéèrè èyíkéyìí",
        practiseTitle = "Ìdánrawò",
        practiseDetail = "Gbìyànjú àwọn ìbéèrè díẹ̀",
        planTitle = "Gba ètò ìkẹ́kọ̀ọ́",
        planDetail = "Fún àwọn ìdánwò rẹ",
        practiseDraft = "Fún mi ní ìbéèrè ìdánrawò mẹ́ta lórí {topic}, ọ̀kan lẹ́yìn èkejì.",
        practiseDraftAny = "Fún mi ní ìbéèrè ìdánrawò mẹ́ta lórí ohun tí mò ń kọ́, ọ̀kan lẹ́yìn èkejì.",
        planDraft = "Ṣe ètò ìkẹ́kọ̀ọ́ fún mi fún àwọn ìdánwò mi nínú ",
    ),
    subject = SubjectCopy(
        back = "Gbogbo àwọn kókó-ẹ̀kọ́",
        progress = "{done} nínú {total} ni o ti kọ́",
        progressLabel = "Ìlọsíwájú",
        learnt = "Ti kọ́",
        ready = "Ti ṣetán",
        notStarted = "Kò tíì bẹ̀rẹ̀",
        goal = "Ohun tí o béèrè",
        lessonsCompleted = "{completed} nínú {total} ìkọ́ni",
        topicsLoading = "Ń kó àkòrí jọ...",
    ),
    plan = PlanCopy(
        edit = "Ṣàtúnṣe",
        buildFailed = "A kò lè ṣe ètò rẹ.",
        tryAgain = "Tun gbìyànjú",
    ),
    planBuilding = PlanBuildingCopy(
        making = "À ń ṣe ètò rẹ…",
    ),
    you = YouCopy(
        progress = "Ìtẹ̀síwájú rẹ",
        details = "Àwọn àlàyé rẹ",
        country = "Orílẹ̀-èdè",
        language = "Èdè ìkẹ́kọ̀ọ́",
        grade = "Ìpele",
        editSubjects = "Ṣàtúnṣe àwọn kókó-ẹ̀kọ́ rẹ",
        practice = "Ìdánrawò rẹ",
        practiceRight = "{right} nínú {answered} ló tọ̀nà",
        practiceNone = "Kò sí ìdánrawò síbẹ̀.",
        change = "Yí i padà",
        account = "Àkọọ́lẹ̀ rẹ",
        learningAs = "{name} ló ń kẹ́kọ̀ọ́",
        switchLearner = "Yí akẹ́kọ̀ọ́ padà",
        manageLearners = "Àwọn akẹ́kọ̀ọ́",
        signOut = "Jáde",
        onMyOwn = "Mò ń kẹ́kọ̀ọ́ fúnra mi",
    ),
    level = LevelCopy(
        undergraduate = "Akẹ́kọ̀ọ́ ìpele àkọ́kọ́ yunifásítì",
        graduate = "Akẹ́kọ̀ọ́ ìpele gíga yunifásítì",
    ),
    details = DetailsCopy(
        back = "Padà",
        title = "Àlàyé rẹ",
        save = "Fi àwọn àyípadà pamọ́",
        askTitle = "Ṣé kí a ṣe ètò tuntun fún àlàyé yìí?",
        askBody = "Ètò tuntun yóò rọ́pò èyí tí o ní.",
        newPlan = "Ṣe ètò tuntun",
        keepPlan = "Pa ètò mi mọ́",
    ),
    voice = VoiceNoteCopy(
        title = "Ẹ̀kọ́ ohùn",
        start = "Bẹ̀rẹ̀",
        note = "graspy ń fi ohùn rẹ ránṣẹ́ láti yẹ ìdáhùn rẹ wò.",
        ok = "Ó dáa",
    ),
    chat = ChatCopy(
        openTutor = "Béèrè lọ́wọ́ graspy",
        newTutorMessage = "Ìfiránṣẹ́ tuntun láti ọ̀dọ̀ graspy",
        draftPlaceholderTopic = "Béèrè graspy nípa {topic}",
        aiTutorTitle = "Olùkọ́ graspy",
        aiTutorWelcome = "Ẹ káàbọ̀! Béèrè ohunkóhun lọ́wọ́ mi nípa ẹ̀kọ́ rẹ.",
        send = "Firánṣẹ́",
        stop = "Dúró",
        tutorThinking = "Mo ń ronú…",
        tutorError = "Nǹkan kan ò lọ dáadáa. Tún gbìyànjú.",
        temporaryProblem = "Kò lọ. Tún gbìyànjú.",
        suggestedQuestions = "Àwọn ìbéèrè tí o lè béèrè tẹ̀lé",
        viewUnavailable = "A kò lè fi káàdì yìí hàn.",
        openLesson = "Ṣí ẹ̀kọ́",
        openSubject = "Ṣí kókó-ẹ̀kọ́",
        seeSubjects = "Wo àwọn kókó-ẹ̀kọ́ rẹ",
        activity = mapOf("calculate" to "À ń ṣírò àwọn nọ́mbà...", "open_subject" to "À ń ṣí kókó-ẹ̀kọ́ náà...", "open_topic" to "À ń wá àkòrí náà...", "add_topic" to "À ń fi àkòrí náà kún ètò rẹ...", "propose_path" to "À ń ṣètò ọ̀nà kan...", "change_subjects" to "À ń ṣàtúnṣe àwọn kókó-ẹ̀kọ́ rẹ...", "rebuild_plan" to "À ń múra láti tún ètò rẹ ṣe...", "give_practice" to "Mò ń kọ ìbéèrè fún ọ...", "give_passage" to "Ń kọ àyọkà kan fún ọ..."),
        planChangeFailed = "Àwọn kókó-ẹ̀kọ́ rẹ kò yí padà. Tún gbìyànjú.",
        changingPlan = "À ń ṣe àtúnṣe ètò rẹ...",
        confirmTitle = "Jẹ́rìí sí àtúnṣe sí ètò rẹ",
        confirmRebuild = "Ṣé kí a tún ètò rẹ ṣe? Ìlọsíwájú rẹ yóò parẹ́.",
        confirmRemove = "Ṣé kí a yọ {subjects} kúrò? Ìlọsíwájú wọn yóò parẹ́.",
        confirmYes = "Bẹ́ẹ̀ni, ṣe é",
        confirmNo = "Fi ètò mi sílẹ̀ bí ó ṣe wà",
        subjectsChanged = "A ti ṣàtúnṣe àwọn kókó-ẹ̀kọ́ rẹ.",
        topicAdded = "A ti fi “{topic}” kún {subject}.",
        pathAdded = "A ti fi ọ̀nà “{subject}” kún ètò rẹ.",
        pathTitle = "Ọ̀nà ẹ̀kọ́",
        pathPlanning = "À ń ṣètò ọ̀nà sí {goal}...",
        pathFailed = "A kò lè ṣètò ọ̀nà sí {goal}. Tún gbìyànjú nígbà míì.",
        pathSummary = "Àkòrí {count}, láti {from} dé {to}",
        pathSummaryOneLevel = "Àkòrí {count} ní {level}",
        pathMore = "àti {count} míràn",
        pathAccept = "Fi ọ̀nà yìí kún un",
        pathNotNow = "Kì í ṣe báyìí",
        topicReady = "“{topic}” ti ṣetán nígbà tí o bá ṣetán.",
        subjectReady = "{subject} ti ṣetán nígbà tí o bá ṣetán.",
    ),
    ask = AskCopy(
        currentTopic = "Àkòrí rẹ báyìí",
        open = "Ṣí ìjíròrò",
        recent = "Àwọn ìjíròrò àìpẹ́",
        anythingTitle = "Béèrè ní gbogbogbòò",
        anything = "Béèrè ohunkóhun",
        chooseTopic = "Yan kókó-ẹ̀kọ́ kan",
        change = "Yí padà",
        changeTitle = "Yí àkòrí padà",
        close = "Pa á dé",
        anythingWelcome = "Béèrè ohunkóhun lọ́wọ́ mi.",
        anythingPlaceholder = "Béèrè ohunkóhun lọ́wọ́ graspy",
        allOf = "Gbogbo {subject}",
        wholeSubject = "Gbogbo kókó-ẹ̀kọ́ náà",
    ),
    lesson = TopicLessonCopy(
        loading = "À ń múra ẹ̀kọ́ rẹ sílẹ̀",
        loadFailed = "Ẹ̀kọ́ náà kò ṣí",
        tryAgain = "Gbìyànjú lẹ́ẹ̀kan sí i",
        backTo = "Padà sí {subject}",
    ),
    onboarding = PlanOnboardingCopy(
        stepOf = "Ìgbésẹ̀ {current} nínú {total}",
        back = "Padà",
        next = "Tẹ̀síwájú",
        start = "Bẹ̀rẹ̀ ẹ̀kọ́",
        settingUp = "À ń ṣètò rẹ̀...",
        steps = PlanOnboardingStepsCopy(
            profile = PlanOnboardingStepsProfileCopy(
                title = "Nípa rẹ",
            ),
            subjects = PlanOnboardingStepsSubjectsCopy(
                title = "Àwọn kókó-ẹ̀kọ́ rẹ",
            ),
        ),
        profile = PlanOnboardingProfileCopy(
            countryLabel = "Orílẹ̀-èdè",
            countryPlaceholder = "Wá orílẹ̀-èdè",
            languageLabel = "Èdè",
            languagePlaceholder = "Yan èdè kan",
            gradeLabel = "Kíláàsì",
            gradePlaceholder = "Yan kíláàsì rẹ",
            suggested = "Àbá",
            allCountries = "Gbogbo orílẹ̀-èdè",
            allLanguages = "Gbogbo èdè",
            noResults = "Kò sí èsì",
            courseLabel = "Ẹ̀ka ẹ̀kọ́",
            coursePlaceholder = "Fún àpẹẹrẹ, Accounting",
            gradeNeedsCountry = "Kọ́kọ́ yan orílẹ̀-èdè rẹ",
            gradesLoading = "À ń wá àwọn kíláàsì…",
            gradesFailed = "Àwọn kíláàsì kò ṣí. Ṣàyẹ̀wò ìsopọ̀ rẹ.",
            systemLabel = "Ètò ilé-ìwé",
            afterSchool = "Lẹ́yìn ilé-ìwé gíga",
        ),
        subjects = PlanOnboardingSubjectsCopy(
            heading = "Àwọn kókó-ẹ̀kọ́",
            recommended = "A dábàá rẹ̀",
            limit = "Kókó-ẹ̀kọ́ {limit} ló pọ̀ jù.",
            finding = "À ń wá àwọn kókó-ẹ̀kọ́…",
            loadFailed = "Àwọn kókó-ẹ̀kọ́ kò ṣí. Ṣàyẹ̀wò ìsopọ̀ rẹ.",
            tryAgain = "Gbìyànjú lẹ́ẹ̀kan sí i",
        ),
        generating = PlanOnboardingGeneratingCopy(
            title = "À ń ṣe ètò rẹ",
            wait = "Èyí lè gba ìṣẹ́jú kan.",
            failed = "Ètò rẹ kò parí.",
            failedBody = "Ṣàyẹ̀wò ìsopọ̀ rẹ kí o sì tún gbìyànjú.",
            tryAgain = "Gbìyànjú lẹ́ẹ̀kan sí i",
            adjust = "Yí àwọn kókó-ẹ̀kọ́ padà",
            stages = PlanOnboardingGeneratingStagesCopy(
                analyzing = PlanOnboardingGeneratingStagesAnalyzingCopy(
                    label = "À ń ka àlàyé rẹ",
                ),
                generating = PlanOnboardingGeneratingStagesGeneratingCopy(
                    label = "À ń yan àwọn àkòrí",
                ),
                personalizing = PlanOnboardingGeneratingStagesPersonalizingCopy(
                    label = "À ń tò wọ́n lẹ́sẹẹsẹ",
                ),
            ),
        ),
        ready = PlanOnboardingReadyCopy(
            title = "Ètò rẹ ti ṣetán",
            body = "Àkòrí {topics}",
            `continue` = "Bẹ̀rẹ̀",
        ),
        moreSubjects = "+{count} míràn",
    ),
)

private val PIDGIN_LEARN = LearnCopy(
    nav = NavCopy(
        label = "Main",
        home = "Home",
        subjects = "Subjects",
        ask = "Ask",
        you = "You",
    ),
    home = PlanHomeCopy(
        continueTitle = "Continue to learn",
        `continue` = "Continue",
        start = "Start",
        resumeMeta = "{subject} · {grade}",
        subjectsTitle = "Your subjects",
        seeAll = "See all",
        noSubjects = "Your subjects go show here once your plan don ready.",
        topicsCompleted = "{completed} of {total} topics don finish",
        topicsCompletedOf = "of {total} topics don finish",
        startLearning = "Start to learn",
        tryTitle = "Or try new thing",
        askTitle = "Explain one topic",
        askDetail = "Ask any question",
        practiseTitle = "Practise",
        practiseDetail = "Try some questions",
        planTitle = "Get study plan",
        planDetail = "For your exams",
        practiseDraft = "Give me three practice questions on {topic}, one by one.",
        practiseDraftAny = "Give me three practice questions on wetin I dey learn, one by one.",
        planDraft = "Make study plan for me for my exams for ",
    ),
    subject = SubjectCopy(
        back = "All subjects",
        progress = "You don learn {done} of {total}",
        progressLabel = "Progress",
        learnt = "Don learn am",
        ready = "E don ready",
        notStarted = "Never start",
        goal = "Na you ask for this",
        lessonsCompleted = "{completed} of {total} lessons",
        topicsLoading = "Topics dey load...",
    ),
    plan = PlanCopy(
        edit = "Change",
        buildFailed = "We no fit build your plan.",
        tryAgain = "Try again",
    ),
    planBuilding = PlanBuildingCopy(
        making = "We dey make your plan…",
    ),
    you = YouCopy(
        progress = "Your progress",
        details = "Your details",
        country = "Country",
        language = "You dey learn with",
        grade = "Level",
        editSubjects = "Change your subjects",
        practice = "Your practice",
        practiceRight = "{right} of {answered} correct",
        practiceNone = "No practice yet.",
        change = "Change",
        account = "Your account",
        learningAs = "{name} dey learn",
        switchLearner = "Change learner",
        manageLearners = "Learners",
        signOut = "Sign out",
        onMyOwn = "I dey learn by myself",
    ),
    level = LevelCopy(
        undergraduate = "Undergraduate",
        graduate = "Graduate",
    ),
    details = DetailsCopy(
        back = "Go back",
        title = "Your details",
        save = "Save changes",
        askTitle = "Make new plan for these details?",
        askBody = "New plan go replace the one wey you get.",
        newPlan = "Make new plan",
        keepPlan = "Keep my plan",
    ),
    voice = VoiceNoteCopy(
        title = "Voice lessons",
        start = "Start",
        note = "graspy dey send your voice make e check your answers.",
        ok = "OK",
    ),
    chat = ChatCopy(
        openTutor = "Ask graspy",
        newTutorMessage = "New message from graspy",
        draftPlaceholderTopic = "Ask graspy about {topic}",
        aiTutorTitle = "graspy tutor",
        aiTutorWelcome = "How far! Ask me anything about your lesson.",
        send = "Send",
        stop = "Stop",
        tutorThinking = "I dey think…",
        tutorError = "Something no work. Try again.",
        temporaryProblem = "E no go. Try again.",
        suggestedQuestions = "Questions wey you fit ask next",
        viewUnavailable = "We no fit show this card.",
        openLesson = "Open lesson",
        openSubject = "Open subject",
        seeSubjects = "See your subjects",
        activity = mapOf("calculate" to "I dey work the numbers...", "open_subject" to "I dey open the subject...", "open_topic" to "I dey find the topic...", "add_topic" to "I dey add the topic to your plan...", "propose_path" to "I dey plan path...", "change_subjects" to "I dey update your subjects...", "rebuild_plan" to "I dey get ready to build your plan again...", "give_practice" to "I dey write question for you...", "give_passage" to "I dey write passage for you..."),
        planChangeFailed = "Your subjects no change. Try again.",
        changingPlan = "We dey update your plan...",
        confirmTitle = "Confirm say you wan change your plan",
        confirmRebuild = "Build your plan again? Your progress go clear.",
        confirmRemove = "Remove {subjects}? Dem progress go clear.",
        confirmYes = "Yes, do am",
        confirmNo = "Keep my plan",
        subjectsChanged = "Your subjects don update.",
        topicAdded = "“{topic}” don enter {subject}.",
        pathAdded = "The path “{subject}” don enter your plan.",
        pathTitle = "Learning path",
        pathPlanning = "I dey plan path to {goal}...",
        pathFailed = "I no fit plan path to {goal}. Try again later.",
        pathSummary = "{count} topics, from {from} reach {to}",
        pathSummaryOneLevel = "{count} topics for {level}",
        pathMore = "and {count} more",
        pathAccept = "Add this path",
        pathNotNow = "No be now",
        topicReady = "“{topic}” don ready anytime you ready.",
        subjectReady = "{subject} don ready anytime you ready.",
    ),
    ask = AskCopy(
        currentTopic = "The topic wey you dey now",
        open = "Open chat",
        recent = "Recent chats",
        anythingTitle = "Ask any kind question",
        anything = "Ask anything",
        chooseTopic = "Choose subject",
        change = "Change",
        changeTitle = "Change topic",
        close = "Close",
        anythingWelcome = "Ask me anything.",
        anythingPlaceholder = "Ask graspy anything",
        allOf = "Everything for {subject}",
        wholeSubject = "The whole subject",
    ),
    lesson = TopicLessonCopy(
        loading = "We dey prepare your lesson",
        loadFailed = "The lesson no load",
        tryAgain = "Try again",
        backTo = "Go back to {subject}",
    ),
    onboarding = PlanOnboardingCopy(
        stepOf = "Step {current} of {total}",
        back = "Go back",
        next = "Continue",
        start = "Start to learn",
        settingUp = "E dey set up...",
        steps = PlanOnboardingStepsCopy(
            profile = PlanOnboardingStepsProfileCopy(
                title = "About you",
            ),
            subjects = PlanOnboardingStepsSubjectsCopy(
                title = "Your subjects",
            ),
        ),
        profile = PlanOnboardingProfileCopy(
            countryLabel = "Country",
            countryPlaceholder = "Search countries",
            languageLabel = "Language",
            languagePlaceholder = "Choose language",
            gradeLabel = "Class",
            gradePlaceholder = "Choose your class",
            suggested = "Wetin we suggest",
            allCountries = "All countries",
            allLanguages = "All languages",
            noResults = "Nothing match",
            courseLabel = "Course",
            coursePlaceholder = "For example, Accounting",
            gradeNeedsCountry = "Choose your country first",
            gradesLoading = "We dey find classes…",
            gradesFailed = "The classes no load. Check your network.",
            systemLabel = "School system",
            afterSchool = "After secondary school",
        ),
        subjects = PlanOnboardingSubjectsCopy(
            heading = "Subjects",
            recommended = "We recommend am",
            limit = "No pass {limit} subjects.",
            finding = "We dey find subjects…",
            loadFailed = "The subjects no load. Check your network.",
            tryAgain = "Try again",
        ),
        generating = PlanOnboardingGeneratingCopy(
            title = "We dey build your plan",
            wait = "E fit take one minute.",
            failed = "Your plan no finish.",
            failedBody = "Check your network and try again.",
            tryAgain = "Try again",
            adjust = "Change subjects",
            stages = PlanOnboardingGeneratingStagesCopy(
                analyzing = PlanOnboardingGeneratingStagesAnalyzingCopy(
                    label = "We dey read your details",
                ),
                generating = PlanOnboardingGeneratingStagesGeneratingCopy(
                    label = "We dey choose topics",
                ),
                personalizing = PlanOnboardingGeneratingStagesPersonalizingCopy(
                    label = "We dey arrange dem for order",
                ),
            ),
        ),
        ready = PlanOnboardingReadyCopy(
            title = "Your plan don ready",
            body = "{topics} topics",
            `continue` = "Start",
        ),
        moreSubjects = "+{count} more",
    ),
)

private val ARABIC_LEARN = LearnCopy(
    nav = NavCopy(
        label = "التنقل",
        home = "الرئيسية",
        subjects = "المواد",
        ask = "اسأل",
        you = "أنت",
    ),
    home = PlanHomeCopy(
        continueTitle = "تابع التعلّم",
        `continue` = "تابع",
        start = "ابدأ",
        resumeMeta = "{subject} · {grade}",
        subjectsTitle = "موادك",
        seeAll = "عرض الكل",
        noSubjects = "ستظهر موادك هنا عندما تصبح خطتك جاهزة.",
        topicsCompleted = "أُنجز {completed} من {total} موضوعًا",
        topicsCompletedOf = "من {total} موضوعًا أُنجزت",
        startLearning = "ابدأ التعلّم",
        tryTitle = "أو جرّب شيئًا جديدًا",
        askTitle = "اشرح موضوعًا",
        askDetail = "اطرح أي سؤال",
        practiseTitle = "تدريب",
        practiseDetail = "جرّب بعض الأسئلة",
        planTitle = "احصل على خطة دراسية",
        planDetail = "لامتحاناتك",
        practiseDraft = "أعطني ثلاثة أسئلة تدريبية عن {topic}، سؤالًا تلو الآخر.",
        practiseDraftAny = "أعطني ثلاثة أسئلة تدريبية عمّا أتعلّمه، سؤالًا تلو الآخر.",
        planDraft = "ضع لي خطة دراسية لامتحاناتي في ",
    ),
    subject = SubjectCopy(
        back = "كل المواد",
        progress = "تعلّمت {done} من {total}",
        progressLabel = "التقدم",
        learnt = "تم تعلّمه",
        ready = "جاهز",
        notStarted = "لم يبدأ",
        goal = "ما طلبته",
        lessonsCompleted = "{completed} من {total} دروس",
        topicsLoading = "جارٍ تحميل المواضيع...",
    ),
    plan = PlanCopy(
        edit = "تعديل",
        buildFailed = "تعذّر إنشاء خطتك.",
        tryAgain = "حاول مرة أخرى",
    ),
    planBuilding = PlanBuildingCopy(
        making = "نُعدّ خطتك…",
    ),
    you = YouCopy(
        progress = "تقدّمك",
        details = "بياناتك",
        country = "البلد",
        language = "لغة التعلّم",
        grade = "المستوى",
        editSubjects = "عدّل موادك",
        practice = "تدريبك",
        practiceRight = "{right} من {answered} صحيحة",
        practiceNone = "لا تدريب بعد.",
        change = "تغيير",
        account = "حسابك",
        learningAs = "يتعلّم الآن: {name}",
        switchLearner = "تبديل المتعلّم",
        manageLearners = "المتعلّمون",
        signOut = "تسجيل الخروج",
        onMyOwn = "أتعلّم بمفردي",
    ),
    level = LevelCopy(
        undergraduate = "طالب بكالوريوس",
        graduate = "دراسات عليا",
    ),
    details = DetailsCopy(
        back = "رجوع",
        title = "بياناتك",
        save = "حفظ التغييرات",
        askTitle = "هل نُعدّ خطة جديدة لهذه البيانات؟",
        askBody = "الخطة الجديدة تحلّ محلّ خطتك الحالية.",
        newPlan = "إعداد خطة جديدة",
        keepPlan = "الإبقاء على خطتي",
    ),
    voice = VoiceNoteCopy(
        title = "دروس صوتية",
        start = "ابدأ",
        note = "يرسل graspy صوتك للتحقّق من إجاباتك.",
        ok = "حسنًا",
    ),
    chat = ChatCopy(
        openTutor = "اسأل graspy",
        newTutorMessage = "رسالة جديدة من graspy",
        draftPlaceholderTopic = "اسأل graspy عن {topic}",
        aiTutorTitle = "graspy المعلم الذكي",
        aiTutorWelcome = "مرحبًا! اسألني عن أي شيء في درسك.",
        send = "إرسال",
        stop = "إيقاف",
        tutorThinking = "أفكّر…",
        tutorError = "حدث خطأ. حاول مرة أخرى.",
        temporaryProblem = "لم يُرسَل. حاول مرة أخرى.",
        suggestedQuestions = "أسئلة يمكنك طرحها بعد ذلك",
        viewUnavailable = "تعذّر عرض هذه البطاقة.",
        openLesson = "افتح الدرس",
        openSubject = "افتح المادة",
        seeSubjects = "اعرض موادك",
        activity = mapOf("calculate" to "نحسب الأرقام...", "open_subject" to "نفتح المادة...", "open_topic" to "نبحث عن الموضوع...", "add_topic" to "نضيف الموضوع إلى خطتك...", "propose_path" to "نخطط مسارًا...", "change_subjects" to "نحدّث موادك...", "rebuild_plan" to "نستعد لإعادة بناء خطتك...", "give_practice" to "أكتب لك سؤالًا...", "give_passage" to "أكتب لك نصًا للقراءة..."),
        planChangeFailed = "لم تتغيّر موادك. حاول مرة أخرى.",
        changingPlan = "نحدّث خطتك...",
        confirmTitle = "أكّد تغيير خطتك",
        confirmRebuild = "هل تعيد بناء خطتك؟ سيُمحى تقدّمك.",
        confirmRemove = "هل تحذف {subjects}؟ سيُمحى تقدّمها.",
        confirmYes = "نعم، تابع",
        confirmNo = "أبقِ خطتي",
        subjectsChanged = "تم تحديث موادك.",
        topicAdded = "أُضيف «{topic}» إلى {subject}.",
        pathAdded = "أُضيف المسار «{subject}» إلى خطتك.",
        pathTitle = "مسار تعلّم",
        pathPlanning = "نخطط مسارًا إلى {goal}...",
        pathFailed = "تعذّر تخطيط مسار إلى {goal}. حاول لاحقًا.",
        pathSummary = "{count} موضوعًا، من {from} إلى {to}",
        pathSummaryOneLevel = "{count} موضوعًا في {level}",
        pathMore = "و{count} أخرى",
        pathAccept = "أضف هذا المسار",
        pathNotNow = "ليس الآن",
        topicReady = "«{topic}» جاهز متى شئت.",
        subjectReady = "{subject} جاهزة متى شئت.",
    ),
    ask = AskCopy(
        currentTopic = "موضوعك الحالي",
        open = "افتح المحادثة",
        recent = "المحادثات الأخيرة",
        anythingTitle = "اسأل بشكل عام",
        anything = "اسأل عن أي شيء",
        chooseTopic = "اختر مادة",
        change = "تغيير",
        changeTitle = "غيّر الموضوع",
        close = "إغلاق",
        anythingWelcome = "اسألني عن أي شيء.",
        anythingPlaceholder = "اسأل graspy عن أي شيء",
        allOf = "كل {subject}",
        wholeSubject = "المادة كلها",
    ),
    lesson = TopicLessonCopy(
        loading = "نحضّر درسك",
        loadFailed = "تعذّر تحميل الدرس",
        tryAgain = "حاول مرة أخرى",
        backTo = "العودة إلى {subject}",
    ),
    onboarding = PlanOnboardingCopy(
        stepOf = "الخطوة {current} من {total}",
        back = "رجوع",
        next = "التالي",
        start = "ابدأ التعلّم",
        settingUp = "جارٍ الإعداد...",
        steps = PlanOnboardingStepsCopy(
            profile = PlanOnboardingStepsProfileCopy(
                title = "عنك",
            ),
            subjects = PlanOnboardingStepsSubjectsCopy(
                title = "موادك",
            ),
        ),
        profile = PlanOnboardingProfileCopy(
            countryLabel = "البلد",
            countryPlaceholder = "ابحث عن بلد",
            languageLabel = "اللغة",
            languagePlaceholder = "اختر لغة",
            gradeLabel = "الصف",
            gradePlaceholder = "اختر صفّك",
            suggested = "مقترح",
            allCountries = "كل البلدان",
            allLanguages = "كل اللغات",
            noResults = "لا نتائج",
            courseLabel = "التخصص",
            coursePlaceholder = "مثلًا: المحاسبة",
            gradeNeedsCountry = "اختر بلدك أولًا",
            gradesLoading = "نبحث عن الصفوف…",
            gradesFailed = "تعذّر تحميل الصفوف. تحقّق من اتصالك.",
            systemLabel = "النظام التعليمي",
            afterSchool = "بعد المرحلة الثانوية",
        ),
        subjects = PlanOnboardingSubjectsCopy(
            heading = "المواد",
            recommended = "موصى بها",
            limit = "حتى {limit} مواد.",
            finding = "نبحث عن المواد…",
            loadFailed = "تعذّر تحميل المواد. تحقّق من اتصالك.",
            tryAgain = "حاول مرة أخرى",
        ),
        generating = PlanOnboardingGeneratingCopy(
            title = "نُعدّ خطتك",
            wait = "قد يستغرق هذا دقيقة.",
            failed = "لم تكتمل خطتك.",
            failedBody = "تحقّق من اتصالك وحاول مرة أخرى.",
            tryAgain = "حاول مرة أخرى",
            adjust = "تغيير المواد",
            stages = PlanOnboardingGeneratingStagesCopy(
                analyzing = PlanOnboardingGeneratingStagesAnalyzingCopy(
                    label = "نقرأ بياناتك",
                ),
                generating = PlanOnboardingGeneratingStagesGeneratingCopy(
                    label = "نختار المواضيع",
                ),
                personalizing = PlanOnboardingGeneratingStagesPersonalizingCopy(
                    label = "نرتّبها",
                ),
            ),
        ),
        ready = PlanOnboardingReadyCopy(
            title = "خطتك جاهزة",
            body = "{topics} موضوعًا",
            `continue` = "ابدأ",
        ),
        moreSubjects = "+{count} أخرى",
    ),
)
