package com.latentic.graspy.localization

/** The app in Pidgin. */
internal val PIDGIN_COPY = AppCopy(
    topics = mapOf(
        "multiplication" to "Times tables", "number" to "Numbers and counting",
        "operations" to "Adding and sharing", "time" to "Telling the time",
        "money" to "Naira and kobo", "shapes" to "Shapes", "fractions" to "Fractions",
        "alphabet" to "Letters and sounds",
    ),
    transcript = "Wetin graspy hear",
    notUnderstoodFeedback = "I no hear any number. Talk the answer again.",
    microphoneNeeded = "Allow the microphone make e record your answer.",
    recordingNotStarted = "Microphone no start. Try again.",
    recordingNotSaved = "Your answer no save. Try again.",
    lesson = LessonCopy(
        teacherSpeaking = "Teacher dey talk",
        yourTurn = "Your turn",
        sayItYourWay = "Talk am your own way.",
        speakNow = "Talk now…",
        recordTable = "Record your answer",
        stopAndSend = "I'm done",
        sending = "Dey send…",
        analysing = "Dey check your answer…",
        notUnderstoodFeedback = "I no hear the %1\$s times table. Talk am again slowly.",
        playAgain = "Hear am again",
        teacherAudioFailed = "Teacher voice no load.",
        waitingForTeacher = "We dey check with your teacher…",
        noSpeech = "I no hear you. Talk am again.",
        couldNotCheck = "I no fit check that one. Talk am again.",
        learnFact = "%1\$s times %2\$s na %3\$s.",
        correctShort = "Correct!",
        tryAgain = "Good try. Talk am again.",
        loading = "We dey bring your lesson…",
        loadFailed = "Your lesson no load.",
    ),
    home = HomeCopy(
        title = "Your lessons",
        loading = "Dey bring your lessons…",
        loadFailed = "Your lessons no load.",
        retry = "Try again",
        noLessons = "No lesson dey for your class yet.",
        mastered = "You sabi am",
        learnt = "Don learn am",
        started = "Don start",
        untouched = "Never start",
        badges = "Your badges",
        oneMoreDay = "One more better day for %1\$s go win im badge.",
        almostThere = "You don near",
        startHere = "START HERE",
    ),
)
