package com.latentic.graspy.localization

/** The app in Yoruba. */
internal val YORUBA_COPY = AppCopy(
    topics = mapOf(
        "multiplication" to "Àwọn tábìlì ìsọdipúpọ̀", "number" to "Nọ́mbà àti kíka",
        "operations" to "Ìlàpọ̀ àti pínpín", "time" to "Kíka aago",
        "money" to "Náírà àti kọ̀bọ̀", "shapes" to "Àwọn ìrísí", "fractions" to "Ìdá",
        "alphabet" to "Lẹ́tà àti ohùn",
    ),
    transcript = "Ohun tí graspy gbọ́",
    notUnderstoodFeedback = "Mi ò gbọ́ nọ́ńbà kankan. Tún ìdáhùn náà sọ.",
    microphoneNeeded = "Gba gbohùngbohùn láàyè láti gba ìdáhùn rẹ sílẹ̀.",
    recordingNotStarted = "Gbohùngbohùn kò bẹ̀rẹ̀. Tún gbìyànjú.",
    recordingNotSaved = "A kò tọ́jú ìdáhùn rẹ. Tún gbìyànjú.",
    lesson = LessonCopy(
        teacherSpeaking = "Olùkọ́ ń sọ̀rọ̀",
        yourTurn = "Àkókò rẹ",
        sayItYourWay = "Sọ ọ́ bí o ṣe fẹ́.",
        speakNow = "Sọ̀rọ̀ báyìí…",
        recordTable = "Gba ìdáhùn rẹ sílẹ̀",
        stopAndSend = "Mo ti parí",
        sending = "Ń fi ránṣẹ́…",
        analysing = "Ń yẹ ìdáhùn rẹ wò…",
        notUnderstoodFeedback = "Mi ò gbọ́ table %1\$s. Tún un sọ díẹ̀díẹ̀.",
        playAgain = "Tún gbọ́",
        teacherAudioFailed = "Ohùn olùkọ́ kò ṣí.",
        waitingForTeacher = "À ń ṣàyẹ̀wò pẹ̀lú olùkọ́ rẹ…",
        noSpeech = "Mi ò gbọ́ ọ. Tún un sọ.",
        couldNotCheck = "Mi ò lè ṣàyẹ̀wò rẹ̀. Tún un sọ.",
        learnFact = "%1\$s ìlọ́po %2\$s jẹ́ %3\$s.",
        correctShort = "Ó tọ́!",
        tryAgain = "Ìgbìyànjú dára. Tún un sọ.",
        loading = "À ń mú ẹ̀kọ́ rẹ bọ̀…",
        loadFailed = "Ẹ̀kọ́ rẹ kò ṣí.",
    ),
    home = HomeCopy(
        title = "Àwọn ẹ̀kọ́ rẹ",
        loading = "Ń mú àwọn ẹ̀kọ́ rẹ wá…",
        loadFailed = "Àwọn ẹ̀kọ́ rẹ kò ṣí.",
        retry = "Tún gbìyànjú",
        noLessons = "Kò sí ẹ̀kọ́ fún kíláàsì rẹ síbẹ̀.",
        mastered = "Ti mọ̀",
        learnt = "Ti kọ́",
        started = "Ti bẹ̀rẹ̀",
        untouched = "Kò tíì",
        badges = "Àwọn àmì ẹ̀yẹ rẹ",
        oneMoreDay = "Ọjọ́ dáadáa kan sí i lórí %1\$s yóò gba ààmì ẹ̀yẹ rẹ̀.",
        almostThere = "Ó ku díẹ̀",
        startHere = "BẸ̀RẸ̀ NÍBÍ",
    ),
    onboarding = OnboardingCopy(
        whatClass = "Kíláàsì rẹ",
        whichLanguage = "Èdè ẹ̀kọ́",
        lessonLanguageNote = "Olùkọ́ ń sọ Gẹ̀ẹ́sì, Yorùbá tàbí Pidgin.",
        whichInterface = "Èdè app",
        followLessons = "Èdè kan náà pẹ̀lú ẹ̀kọ́",
        next = "Tẹ̀síwájú",
        classAndLanguage = "Kíláàsì àti èdè",
        detectLanguage = "Jẹ́ kí graspy gbọ́",
        classLabels = NIGERIAN_CLASS_LABELS,
    ),
)
