#!/usr/bin/env python3
"""Compile the lesson plan JSON files into the Python module the Worker ships.

The JSON files under src/app/voice/lesson_plans/plans are the source of truth; the Worker bundle
carries only Python, so this writes src/app/voice/lesson_plans/catalogue.py. A test fails when the
module is stale.
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2] / "src" / "app" / "voice" / "lesson_plans"
PLANS = ROOT / "plans"
MODULE = ROOT / "catalogue.py"


def render() -> str:
    plans = [json.loads(path.read_text()) for path in sorted(PLANS.rglob("*.json"))]
    body = json.dumps(plans, ensure_ascii=False, indent=1, sort_keys=True)
    return (
        '"""Generated by scripts/voice/build_catalogue.py from lesson_plans/plans; do not edit."""\n'
        "# ruff: noqa\n"
        "# fmt: off\n\n"
        f"PLANS = {body}\n"
    )


def main() -> None:
    content = render()
    if "--check" in sys.argv:
        sys.exit(0 if MODULE.exists() and MODULE.read_text() == content else 1)
    MODULE.write_text(content)
    print(f"wrote {MODULE} with {content.count(chr(10))} lines")


if __name__ == "__main__":
    main()
