/** Every ISO 3166-1 region with the languages its learners are offered
    first, its main language first. English follows for most. */
export const COUNTRY_LANGUAGES: Record<string, string[]> = {
  AD: ["ca", "es", "fr", "en"],
  AE: ["ar", "en"],
  AF: ["ps", "fa", "en"],
  AG: ["en"],
  AI: ["en"],
  AL: ["sq", "en"],
  AM: ["hy", "en"],
  AO: ["pt", "en"],
  AQ: ["en"],
  AR: ["es", "en"],
  AS: ["en", "sm"],
  AT: ["de", "en"],
  AU: ["en"],
  AW: ["nl", "en"],
  AX: ["sv", "fi", "en"],
  AZ: ["az", "ru", "en"],
  BA: ["bs", "hr", "sr", "en"],
  BB: ["en"],
  BD: ["bn", "en"],
  BE: ["nl", "fr", "en"],
  BF: ["fr", "en"],
  BG: ["bg", "en"],
  BH: ["ar", "en"],
  BI: ["fr", "rn", "en"],
  BJ: ["fr", "en"],
  BL: ["fr", "en"],
  BM: ["en"],
  BN: ["ms", "en"],
  BO: ["es", "qu", "ay", "en"],
  BQ: ["nl", "en"],
  BR: ["pt", "en"],
  BS: ["en"],
  BT: ["dz", "en"],
  BV: ["no"],
  BW: ["en", "tn"],
  BY: ["be", "ru", "en"],
  BZ: ["en", "es"],
  CA: ["en", "fr"],
  CC: ["en"],
  CD: ["fr", "sw", "ln", "en"],
  CF: ["fr", "sg", "en"],
  CG: ["fr", "ln", "en"],
  CH: ["de", "fr", "it", "en"],
  CI: ["fr", "en"],
  CK: ["en", "rar"],
  CL: ["es", "en"],
  CM: ["fr", "en"],
  CN: ["zh", "en"],
  CO: ["es", "en"],
  CR: ["es", "en"],
  CU: ["es", "en"],
  CV: ["pt", "en"],
  CW: ["nl", "en"],
  CX: ["en"],
  CY: ["el", "tr", "en"],
  CZ: ["cs", "en"],
  DE: ["de", "en"],
  DJ: ["fr", "ar", "en"],
  DK: ["da", "en"],
  DM: ["en"],
  DO: ["es", "en"],
  DZ: ["ar", "fr", "en"],
  EC: ["es", "en"],
  EE: ["et", "en"],
  EG: ["ar", "en"],
  EH: ["ar", "es", "fr", "en"],
  ER: ["ti", "ar", "en"],
  ES: ["es", "en"],
  ET: ["am", "en"],
  FI: ["fi", "sv", "en"],
  FJ: ["en", "fj", "hi"],
  FK: ["en"],
  FM: ["en"],
  FO: ["fo", "da", "en"],
  FR: ["fr", "en"],
  GA: ["fr", "en"],
  GB: ["en"],
  GD: ["en"],
  GE: ["ka", "en"],
  GF: ["fr"],
  GG: ["en"],
  GH: ["en"],
  GI: ["en"],
  GL: ["kl", "da", "en"],
  GM: ["en"],
  GN: ["fr", "en"],
  GP: ["fr"],
  GQ: ["es", "fr", "pt", "en"],
  GR: ["el", "en"],
  GS: ["en"],
  GT: ["es", "en"],
  GU: ["en", "ch"],
  GW: ["pt", "en"],
  GY: ["en"],
  HK: ["zh", "en"],
  HM: ["en"],
  HN: ["es", "en"],
  HR: ["hr", "en"],
  HT: ["fr", "ht", "en"],
  HU: ["hu", "en"],
  ID: ["id", "en"],
  IE: ["en", "ga"],
  IL: ["he", "ar", "en"],
  IM: ["en"],
  IN: ["hi", "en", "bn", "te", "mr", "ta", "ur", "gu", "kn", "ml"],
  IO: ["en"],
  IQ: ["ar", "ku", "en"],
  IR: ["fa", "en"],
  IS: ["is", "en"],
  IT: ["it", "en"],
  JE: ["en", "fr"],
  JM: ["en"],
  JO: ["ar", "en"],
  JP: ["ja", "en"],
  KE: ["sw", "en"],
  KG: ["ky", "ru", "en"],
  KH: ["km", "en"],
  KI: ["en", "gil"],
  KM: ["ar", "fr"],
  KN: ["en"],
  KP: ["ko"],
  KR: ["ko", "en"],
  KW: ["ar", "en"],
  KY: ["en"],
  KZ: ["kk", "ru", "en"],
  LA: ["lo", "en"],
  LB: ["ar", "en", "fr"],
  LC: ["en"],
  LI: ["de", "en"],
  LK: ["si", "ta", "en"],
  LR: ["en"],
  LS: ["en", "st"],
  LT: ["lt", "en"],
  LU: ["fr", "de", "lb", "en"],
  LV: ["lv", "en"],
  LY: ["ar", "en"],
  MA: ["ar", "fr", "en"],
  MC: ["fr", "en"],
  MD: ["ro", "ru", "en"],
  ME: ["sr", "en"],
  MF: ["fr", "en"],
  MG: ["mg", "fr", "en"],
  MH: ["en", "mh"],
  MK: ["mk", "en"],
  ML: ["fr", "en"],
  MM: ["my", "en"],
  MN: ["mn", "en"],
  MO: ["zh", "pt", "en"],
  MP: ["en"],
  MQ: ["fr"],
  MR: ["ar", "fr"],
  MS: ["en"],
  MT: ["mt", "en"],
  MU: ["en", "fr"],
  MV: ["dv", "en"],
  MW: ["en", "ny"],
  MX: ["es", "en"],
  MY: ["ms", "en", "zh", "ta"],
  MZ: ["pt", "en"],
  NA: ["en", "af"],
  NC: ["fr"],
  NE: ["fr", "en"],
  NF: ["en"],
  NG: ["en", "pcm", "yo", "ha", "ig"],
  NI: ["es", "en"],
  NL: ["nl", "en"],
  NO: ["no", "en"],
  NP: ["ne", "en"],
  NR: ["en"],
  NU: ["en"],
  NZ: ["en", "mi"],
  OM: ["ar", "en"],
  PA: ["es", "en"],
  PE: ["es", "en"],
  PF: ["fr"],
  PG: ["en", "tpi", "ho"],
  PH: ["en", "fil"],
  PK: ["ur", "en"],
  PL: ["pl", "en"],
  PM: ["fr"],
  PN: ["en"],
  PR: ["es", "en"],
  PS: ["ar", "en"],
  PT: ["pt", "en"],
  PW: ["en", "pau"],
  PY: ["es", "gn", "en"],
  QA: ["ar", "en"],
  RE: ["fr"],
  RO: ["ro", "en"],
  RS: ["sr", "en"],
  RU: ["ru", "en"],
  RW: ["rw", "en", "fr"],
  SA: ["ar", "en"],
  SB: ["en"],
  SC: ["en", "fr", "crs"],
  SD: ["ar", "en"],
  SE: ["sv", "en"],
  SG: ["en", "zh", "ms", "ta"],
  SH: ["en"],
  SI: ["sl", "en"],
  SJ: ["no"],
  SK: ["sk", "en"],
  SL: ["en"],
  SM: ["it", "en"],
  SN: ["fr", "wo", "en"],
  SO: ["so", "ar", "en"],
  SR: ["nl", "en"],
  SS: ["en", "ar"],
  ST: ["pt"],
  SV: ["es", "en"],
  SX: ["nl", "en"],
  SY: ["ar", "en", "ku"],
  SZ: ["en", "ss"],
  TC: ["en"],
  TD: ["fr", "ar", "en"],
  TF: ["fr"],
  TG: ["fr", "en"],
  TH: ["th", "en"],
  TJ: ["tg", "ru", "en"],
  TK: ["en"],
  TL: ["pt", "tet", "en"],
  TM: ["tk", "ru", "en"],
  TN: ["ar", "fr", "en"],
  TO: ["en", "to"],
  TR: ["tr", "en"],
  TT: ["en"],
  TV: ["en"],
  TW: ["zh", "en"],
  TZ: ["sw", "en"],
  UA: ["uk", "ru", "en"],
  UG: ["en", "sw"],
  UM: ["en"],
  US: ["en", "es"],
  UY: ["es", "en"],
  UZ: ["uz", "ru", "en"],
  VA: ["it", "la", "en"],
  VC: ["en"],
  VE: ["es", "en"],
  VG: ["en"],
  VI: ["en"],
  VN: ["vi", "en"],
  VU: ["bi", "fr", "en"],
  WF: ["fr"],
  WS: ["sm", "en"],
  YE: ["ar", "en"],
  YT: ["fr"],
  ZA: ["en", "af", "zu", "xh"],
  ZM: ["en"],
  ZW: ["en", "sn", "nd"],
};
